apiVersion: v1
kind: Secret
metadata:
    name: livekit-config
stringData:
    livekit.yaml: ENC[AES256_GCM,data:65+8XANFUbippdQ6XYlBJ/AmkgfN/fql1RxYQOMCOM0KQ8dn8z1kRhoMTBpl0WOkyDoaM/fgOh8v0Y0/Lq31zGG3yMDAYa6+0WrgVZlBdxeqzZFcRMG06sujqFpEyVWcXPbYy0Nh8QAWRbsjPxTOKb1FQZ39rPIM68wHe0faEQm4kg0AZvh/ShUYWDOKPPC0dkyVZopTUz8EbkvAnnDkCFmQQhNcHl/EP9Z+IOvtHiphbnyutbIAMk+CWEfPpU5CXILn9oSz+ROKKbk8vr0G8ZwBPBUu/vTT+mqx1JwJI5yUB6Qjphpja1MT8AgcNb5Qfvtrbfbp2fVp+27T1Yp6Xfg1jovTR7UOl3R5GK8FmMdJGLSEXw5V/LyBThz+4uTdBOS8vQh6pYo+LfB14ee8NS8kzLka2N/aYHLdet2XemrX/fPuJrbRccoWeGV9HpKGjEFabvv89A7LesYKBx6MwihQtJNOz5uak0+cYKY4KY3ugTDHxSln+HXF4bc1iM1OtS4h,iv:+fQYiaG39mkgzRm7VWWxQZ/ftgIclZBZHSKi4HO31w8=,tag:K+doIN83oZPNUNmlbUQj9A==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeTg2c0JDOUFOV2RZZ1pm
            Q1dCdmF1N0IyZFdqaDZ4ZlhSbGdMVmdoZkZFCnpSNjgwcUpxMXl2NmhrUDJMWGdt
            bElMOWYyNWwxcFZ1ZVdPdDRvcnhFb3MKLS0tIHRSSE9yTlo4K3NBUnJBdzNwNTRu
            UWlLZXNvMlBPQjZWd21SYXhtSFF3dW8KKRIn7pnSiQ7dqbI8Zo+WkctIcVBUuBSG
            Q572YPWEu60AaCA0OYia9lTeMCAcw48+VvJeW2Am2WemwaVb6IiwTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-19T04:47:39Z"
    mac: ENC[AES256_GCM,data:Nk5iSK7sRha2It6155+ruELtxoT3Ih78wp5gce2NNUX71KR35VxwrU/DsM1HbqJ89Nhk9K1pvFn1BcC3piH9rA62SLZihtOOUsVJ/Axo3LXW+BUnPMHUAVHUXuiG183hhRv6YGmHCO7e0qb2DOTrOwxHkUaPKAgeMzAYvu4jGgs=,iv:iStf85nVmtdkOQcT4Tsf5oG+U4dsj2qdf8TBha2f+i8=,tag:dfTaAl6mfdon6j0/qCM8vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: lk-jwt-secret
stringData:
    LIVEKIT_KEY: ENC[AES256_GCM,data:E8zjfcUv4RvINLPNjPL1,iv:IC8BhxEwx1qjZeS2KSmZZOxEal/ZwQjEdpInYUHKhA8=,tag:xBEa0ksB1rnJQoWLcLnStQ==,type:str]
    LIVEKIT_SECRET: ENC[AES256_GCM,data:NrvOJsxeSO3ZrED3m7NZlJN9QEv3yKw6NbqORsgezxVdugzyAfCyAZAsexI=,iv:oTaLp5Zc403mB/CFgXyvFvzgEzd3Ih8o6jlr8Ol63t8=,tag:2RhbcGfhJjAPEUvVqXxQKg==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeTg2c0JDOUFOV2RZZ1pm
            Q1dCdmF1N0IyZFdqaDZ4ZlhSbGdMVmdoZkZFCnpSNjgwcUpxMXl2NmhrUDJMWGdt
            bElMOWYyNWwxcFZ1ZVdPdDRvcnhFb3MKLS0tIHRSSE9yTlo4K3NBUnJBdzNwNTRu
            UWlLZXNvMlBPQjZWd21SYXhtSFF3dW8KKRIn7pnSiQ7dqbI8Zo+WkctIcVBUuBSG
            Q572YPWEu60AaCA0OYia9lTeMCAcw48+VvJeW2Am2WemwaVb6IiwTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-19T04:47:39Z"
    mac: ENC[AES256_GCM,data:Nk5iSK7sRha2It6155+ruELtxoT3Ih78wp5gce2NNUX71KR35VxwrU/DsM1HbqJ89Nhk9K1pvFn1BcC3piH9rA62SLZihtOOUsVJ/Axo3LXW+BUnPMHUAVHUXuiG183hhRv6YGmHCO7e0qb2DOTrOwxHkUaPKAgeMzAYvu4jGgs=,iv:iStf85nVmtdkOQcT4Tsf5oG+U4dsj2qdf8TBha2f+i8=,tag:dfTaAl6mfdon6j0/qCM8vw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
