apiVersion: v1
kind: Secret
metadata:
    name: zulip-secret
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:531U1/wDW1M6yeOWn7rDKmUhz3fuwIwZozmypmz0Mcfma4+b2B5Z/Kz80GtzRHNcN6I=,iv:15fumVNLRNIhit5i6aHJiE5Q+kpXq8dRRL0Erm8Iyhs=,tag:MfeKI6I/TwXffxi9xTfkpg==,type:str]
    ZULIP_ADMINISTRATOR: ENC[AES256_GCM,data:CMzqgb+h5VTlwkDHmnDWjjA=,iv:MbOPEuUr6YL4XzgDZDa05zLZ2zra7ehfu18z5vszrSc=,tag:PGVPo+Njtx8YpAMMfVyONQ==,type:str]
    EMAIL_HOST: ENC[AES256_GCM,data:Ai8gkrYpQ0SFlUROMuSWiw==,iv:lY+EqEjqrUoNN/cv0T0WbwoCreMWFDdgxdVYu/Ee37c=,tag:7AMSBgJxDz+YQn0HfvBrPA==,type:str]
    EMAIL_USER: ENC[AES256_GCM,data:22E1phi3xM5NcD2IJ4gVoWYAYW+HS2cisZopLp3vyfk=,iv:cdBVL2q8pKDYEJ31XeS8D4iV7H+lZWQn0vP3Q53ImZc=,tag:u4eh3LPPMiwQWk6r27cNlw==,type:str]
    EMAIL_PASSWORD: ENC[AES256_GCM,data:OUnKJxDrx7qUBiOlrFYc1mrvdjfsi6osdH7LxuSZhWU=,iv:Bxxiofejx4oIt8pRV1cC4ybLPpz49cM5dvAH6Xehv1c=,tag:94FBJOcSyw3Vkgi2oQEY5A==,type:str]
    RABBITMQ_PASS: ENC[AES256_GCM,data:+MT9uQkPIx124CSbJgHasdXQUgafeihRtF6Uf68SQzE=,iv:wyAiN5u8oZXlDs0I2LCvWCTdwyJvnMzauB79rzemUe0=,tag:23JDyzY1nHCCOs4LbNhpww==,type:str]
    RABBITMQ_ERLANG_COOKIE: ENC[AES256_GCM,data:P2Jw4JgCEihuM5n72I3n7MO/tergTRoCXgm38rKp6A==,iv:IrCe8G9MCdrH8aqAMIyrP0P7ZBixodJkPP+z5bmGdmA=,tag:RWbFyMGAlTY40rWIyJ1FDA==,type:str]
    ZULIP_ORG_ID: ENC[AES256_GCM,data:OZoCxOyVfB3MoMHsgqiLtW3a5H2iZpEDcDfCyLg2NHi7zKkI,iv:+dKPVzRLLYuSK7yX2ze/5RHLQvnovVoHYQsSahDf3OI=,tag:sK1+ZCf8dFroV8WMmpb8dA==,type:str]
    ZULIP_ORG_KEY: ENC[AES256_GCM,data:Pwa1GsfESTeWlG15CSopvLTh1/XNM0P/j2SvakuxrjDGznby6bLzrecEKYQZXHD4pmxoZ68WFXKAsZ/vLIA6yA==,iv:t04rmNNTo75Y+fNMUIP5LHJxgGosBW+gD+Ws3NmUUzc=,tag:Gd+UUayhh8Ay8bLTukQVsQ==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZWdEbkNoY3o1aTltRzFS
            bkVjWFhYblF6UlhJckh5dHR1QUZTNEgvbzFVCjMyb0IzMVdLc3ZITTFoeDBsNlJP
            eDdpcHg2MGpPR1hPU0NhQkZ6aGt5ek0KLS0tIFM3OWVUZWhpQmtlelZCemlTb3lZ
            YmVkeTBmMXFUY3FiMWNEUDIwZkl2enMKNlNt9AyCMFP3K3Y4Kkhqrt54DSQ+5jYr
            A54Ek2pwkrZZcHPYb5tv6EK0M0MWGYS270OCwVdu6GCHqWpwMuzbTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T10:30:46Z"
    mac: ENC[AES256_GCM,data:CTG6oQXncsuKK+QUwMqc71qqwMbB2umHs6P8fDXniODtvkbde8BQ4UQO6ZaaAAx8JzK0xonl71o/E4S64oDTSKnktRayYA6ICAl5k+peiE0+XPINqegHgXPl1doCCj8u51iFlc96LJo2hCaR2FWOt94u9vgeLErO+/mO64niggg=,iv:0wUjw4jOIkP7QQjxJvCWT/odpNqROwKYzdlnt10a6l4=,tag:YxjjaO3EyvBujxkD1L90cg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
