apiVersion: v1
kind: Secret
metadata:
    name: zulip-secret
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:YGjp26IfDjHTIKbzfOvNz+Q66/IxPA8i0N/AryZFklmCmb8ebp+c6GcLm0sxDsosZwM=,iv:pLevSFzndaCjUOvkd1xJ7rLBorhRGxKoOe3HrhALFu4=,tag:F7yelECcqRkfx4x17rBzFQ==,type:str]
    ZULIP_ADMINISTRATOR: ENC[AES256_GCM,data:jQSDK9KrmRE/bTrrC0A7Fpc=,iv:FS5qLD4TNyqDbPn2VnT+8OFTcmLQzBrxEwT7zaWk6fk=,tag:bh4NIZyly2x2CePLIBkLQg==,type:str]
    EMAIL_HOST: ENC[AES256_GCM,data:kNsDfhCFGw5u/Xt8uz+xuQ==,iv:o4MOTIiblUVGoplMz/hsxsOPvMsFBrepjm/K/Vkob0I=,tag:zLNlfMslZ3ZC6r1XXba8fQ==,type:str]
    EMAIL_USER: ENC[AES256_GCM,data:j1xfjsu/7ye5Y9K7mEGPkO7GUSgla6QvwVjzIqusirE=,iv:GK+I5k753wv20YneG8vSRZMllefNjXr/oeYkNb+BKd4=,tag:JH2Y76jZrrx8wGweypEGvw==,type:str]
    EMAIL_PASSWORD: ENC[AES256_GCM,data:a/Y0VVIci7mKWWKeg7G48ZFpWYrwwSum3+27xPgr4hk=,iv:E2Pr15a9SB9ug00r7fVQeR61K2PNB2aAj+R9M7IBM3I=,tag:2iCjaeqeWanvUCb2WTN/ZA==,type:str]
    RABBITMQ_PASS: ENC[AES256_GCM,data:xoSQAae9XBKZH22iz5zzw5F6w99UNutyv5xmhsmzldM=,iv:9ZhJktVub0oz8nix64d2gggqkDuatCqLJiE3fUTWcDM=,tag:Ge3Fh43JgRh2gdMsGJ0XZw==,type:str]
    RABBITMQ_ERLANG_COOKIE: ENC[AES256_GCM,data:dIiIuDnRT+HE0e2Pt0Qs2clXVD+/N912k6PlnLSWrA==,iv:Si2QJ+pvORSDQktnWuJs1GdMLWLtlkJZKYSVczKyz4c=,tag:ur/lygonhbQXDopcH+CdKQ==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbmk5b0wwUEJQV0tycDJP
            U0NjYmZnbGphZHBzSFFNeXNOZ2JPMWZuMTJrClVXVTBnZThiS1NiNEVwaEdSQU1x
            UGdSRThJRU0zTXpDTEdqNWoxR0wyL3cKLS0tIFIrSkVNcmRCdlA3SVJFZXRyM1No
            M0k2WUpQb2Y3V3BmUVIwWDBjcHNwZEEKbq65OTfulJMnuo78uZehC9+Ex3qe6jdg
            PlrA7Nt1jE1D/5utG7G/vxZU2mOtuMww/FSS+ObSnZzwV6Nx46Yaew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-18T08:39:41Z"
    mac: ENC[AES256_GCM,data:jH0yo0kbvcNsHfzqdgSUDi+Sk1jaihFSiW3iI4j1TPmbRNM7/huU0pIl8+EgGiBqcriwjjI0Q7cHlmpKbLqYMikZPXLOZ246jkRNqZMKMl1XHGibN89yGr95hwu8LMneLqYLUUxftoLGD/ZCjXxR/5glEMesWoFyPjSWnx2gLfs=,iv:roOAeKN/YTlIT7437d0W5Urf2zBI1mER+j0B3keB1Wo=,tag:fohD9wBKTaNJWErgMIoyGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
