apiVersion: v1
kind: Secret
metadata:
    name: synapse-db-secret
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:7We9pWYdJg==,iv:CSwr6dqBE95h8SCv5NQuTLw2I2RStawJQqJ9HJco3zE=,tag:Mzc42BRtHg0HVhE0XUR7EQ==,type:str]
    password: ENC[AES256_GCM,data:DO865LcBgaHgrFJZ5nDO7cp9R81RlscM/GdbMJDwT9TnCUF6lQQiaA==,iv:s0ITyGTUxFHrHV5wRU5Q4r66MbSTYLChzK/B5rRg5bo=,tag:LZeWCzmAJ0NoHhN63UCDcw==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWFdHbTZXNDdIMGFEWEhh
            aWVhUHVzYkFpdzI0MnZkcmRFdUtqemdpV0R3CnhQeU4zT1c5dE0yK1ZJUWxzYkFt
            Yng1Q0VST21VMlhramJCaC8xeDZZOUEKLS0tIG5qMFlxTnk2ay9sMHhYYW5wTlY2
            TFdzK2MxUkNZb2RuanhuVFlNcnNvVlUKphQaoT2SVCHvHL31zIeL1yPPv5KlwzJ/
            PZiMT+FPHOvJyxwuda1dQlx9NCAJ2R3yVFz53hsy0GFWZowr/6wurA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-19T04:47:39Z"
    mac: ENC[AES256_GCM,data:RbAHumFxcN30MZSU4XKufx5st4n/VgmOfJ8BogLE2MbWxMjlmLqUSeJ1ygnc0htoyt7OqqQkGzGbmQeWwYd6YIGzbOF1bzIDSb71UcUcC5ap65YaxORc0qJRklQlBA2o6kGDIfEe6xOp82z27ZXMVSgBvONAZnFJdOYq5oKgojM=,iv:ZShexU4JuU0FIdfBSpO7P4iW23sI3g5Agbq+tudRqCo=,tag:MIxRDfx3pbpOXD9KPeMOVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
