apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:gl1HVuGzJgpCWfJOD7z7qGIQ66EXlLVaA5rgMEOUrmA=,iv:3wfXJ2QlRkrWUKYK2hDqj56uNhY8dcaTis6dLZyGBsY=,tag:PDgETfkqSc/PbZUD0gwLzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjREkwS3dMQWFDTjFldmV6
            bjdDTzFYTmhSbWt6YTU4em40SXc5bTR1SkJvCk9KQ3hnNGdueVEvdjlZbDg1UTZX
            MFdGb1JzVThLay9neEdGL1N3Ni91ZDgKLS0tIG9ic090YnlrYkx1Q3ZGb01NZWNI
            b0g2aUVTbmk2SUg3ZnBrUC9xd1dRVWcKFXns+zev5qQwHX4tm+Oln8iYRpEJ57Th
            mSbJS2+szqRqr4oKnda3smLoyYdyT5meiy8pXrBYqr30ccUTlGvgXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-18T16:38:00Z"
    mac: ENC[AES256_GCM,data:QcLivp7TLsU/N3BLq4g23+qHiwemX3WeK51dJtCXRDTTIlDUXF8bHGHMeZkfu4TUJ9S7lr2PaQt4Ugjl0jB48/fa3R6X5B/z3oBIaUxgyttDkvXiwmSPu45sQ7T/BYYRudxQzKVrg+5S0sYa8AypWMpnPXlrS09HH6bfX143di4=,iv:ynWhIUx1P6fHMSZBnqZgai9EabVGpkmnveu/iUIXii8=,tag:2cuA61a8RdUXzdgfmSBorg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
