---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailing-sidecar-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: tailing-sidecar-operator
      version: 0.18.1
      sourceRef:
        kind: HelmRepository
        name: tailing-sidecar
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: disabled # The MutatingWebhookConfiguration repeatedly triggers drift detection
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    certManager:
      enabled: true
