---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/alertmanagerconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager
spec:
  route:
    groupBy: ["alertname", "job"]
    groupInterval: 10m
    groupWait: 1m
    receiver: email
    repeatInterval: 12h
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            value: InfoInhibitor
            matchType: =
      - receiver: heartbeat
        groupInterval: 5m
        groupWait: 0s
        repeatInterval: 5m
        matchers:
          - name: alertname
            value: Watchdog
            matchType: =
      - receiver: email
        matchers:
          - name: severity
            value: critical
            matchType: =
  inhibitRules:
    - equal: ["alertname", "namespace"]
      sourceMatch:
        - name: severity
          value: critical
          matchType: =
        - name: severity
          value: warning
          matchType: =~
    - equal: ["namespace"]
      sourceMatch:
        - name: alertname
          value: InfoInhibitor
          matchType: =
      targetMatch:
        - name: severity
          value: info
          matchType: =
  receivers:
    - name: "null"
    - name: heartbeat
      webhookConfigs:
        - urlSecret:
            name: &secret alertmanager-secret
            key: ALERTMANAGER_HEARTBEAT_URL
    - name: email
      emailConfigs:
        - from: "alert-manager@jmartin.se"
          to: "cluster-alerts@jmartin.se"
          headers:
            - key: subject
              value: >-
                [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}]
                {{- if ne .CommonAnnotations.summary "" }}
                  {{ .CommonAnnotations.summary }}
                {{- else }}
                  {{ .CommonLabels.alertname }}
                {{- end }}
          smarthost: "smtp.mailjet.com:587"
          requireTLS: true
          sendResolved: false
          authUsername: ${SECRET_EMAIL_USERNAME}
          authPassword:
            name: *secret
            key: SMTP_PASSWORD
