---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
  - ./cloudnative-pg-rules.yaml
  - ./secret.sops.yaml
  - ./alertmanagerconfig.yaml
