apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    ALERTMANAGER_HEARTBEAT_URL: ENC[AES256_GCM,data:W90YvhjdwhKp8Ax7BHGctG02A/y4MA/qW9nz4YJAhlM8Wq64/zsjxA+jdOZ0JudnvGbig5bb53o=,iv:pfyrbJXAob7N3/qpKjnE7YLSuD8Ricunz149Q+eA94M=,tag:Anyk+A2kT6ZPcX7J9dOHuQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:CMm80HSInS/pjmOoztAqNYtGSnl9H1D/dKyRXv/IFaA=,iv:R/yt9zvQw6usWsxNFsnlhsfur8KLo1rWs9iratceKGs=,tag:yWBQ/YChOvIotgShWtIcUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXRHQ2cXZRbEp3cERqOFJR
            TEx5bXJBRHRtV2VjOEFucnJEZGlZT2pLTmhnCjF6bng4Nk9ZekxSRk14d1VXVFVa
            cDNXbWQ0V29kVXRwRWJ1WG80MCtjZFUKLS0tIFppYnREOUtLR3dwdHJXNXFPSEdv
            Vyt6d05WL1VFTDllL0ZMYUdRaEx5TFUKU3Erjd7OQKmEdl+fc8yIMUG8ZbIgbR70
            kCNtWcN80/PQ6hwSxpdZHR9I7F0yVou5WizDQRrKxra+jhRaLWN56Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T15:53:44Z"
    mac: ENC[AES256_GCM,data:j7v+UigX58WPG/NGaBhQ2FwVEF/XF5cV1tWAvhtEhSS2vJDBVN/P9kBiam6kqDu364hURKyYUlc+vlEFwKWPcfIL1m1ehz3mGH+yT0g2mY3x9y8GmE/9sB7K6IyuxTpB13MAudw5eOVZFP6x2EJ1jZpkcBptGsQLmp4CH8vfJyY=,iv:OQtJyIsHF8mLCBNPITmG0FgOkG+SVIldfu2y0IIVRlM=,tag:q2gxsxd25pV+DiJ5FBbr+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
