---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multi-scrobbler
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      multiscrobbler:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/foxxmd/multi-scrobbler
              tag: 0.9.1
            env:
              TZ: ${TIMEZONE}
              BASE_URL: https://multiscrobbler.${SECRET_DOMAIN}
              MALOJA_URL: http://maloja:42010
              LASTFM_REDIRECT_URI: https://multiscrobbler.${SECRET_DOMAIN}/lastfm/callback
              SPOTIFY_REDIRECT_URI: https://multiscrobbler.${SECRET_DOMAIN}/callback
              PLEX_URL: http://plex.default:32400
            envFrom:
              - secretRef:
                  name: multi-scrobbler-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 500M
              limits:
                memory: 1024M
    service:
      app:
        controller: multiscrobbler
        ports:
          http:
            port: 9078
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/icon: sh-multi-scrobbler.png
          gethomepage.dev/name: Multi-scrobbler
        className: internal
        hosts:
          - host: "multiscrobbler.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: multiscrobbler
