apiVersion: v1
kind: Secret
metadata:
    name: multi-scrobbler-secret
stringData:
    MALOJA_API_KEY: ENC[AES256_GCM,data:DjHWDeKMzitNL+I4uwHYEolVPvqbxh0epYjfnInJkEg5+oUvGtcZTsJNMxFmKU1H6iglTTKxPayKjuwPreE=,iv:UIC+/SBYNVM/8bi9NctnI+9/UF4RUkj83IYbr9rJDK8=,tag:spD+64XGwuOVD8baRMaREA==,type:str]
    LASTFM_API_KEY: ENC[AES256_GCM,data:KgI8LDf4DJLJUks0g0puNJDWZWj8eTtmvDU0ZDkoWuc=,iv://J6Fp/9hNl9kL000fL1LgQ5fe0EzWITHofcJUBl9dY=,tag:Cs56T6zvW3FsL+rRM4cWfw==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:yHvsiKlK9VaSH5wsQh4O4Mo3yB68NDCdQzOJAMWxCP0=,iv:IdxMzIemYalpe8qn1JXYjvTqfEp0vMDQYFz+1aZgrUg=,tag:3tAwonoVcYDxl1dqqhyBhg==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:au/Z10B3Y1MFOw+aCc87DM/jmkl0QIPqE8psuxdUUE4=,iv:8IP4GC7Lwd2XUfziUi2/B/SbdOxACwfzCPriyFhFJY4=,tag:/U66lR5JLjqR6tJXyhA7aA==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:p6+HfLf/g6LGT/RdXYtkgUnPgNqbbUzDC1V2hAP6Opk=,iv:GGToQ6wf9iW8C+yfTBLkMuAIJb3OBBB6e9xlhJ1mDu4=,tag:bs/jLBLHm3Py4SR6KeQtPA==,type:str]
    PLEX_TOKEN: ENC[AES256_GCM,data:9R85JlRfsUSTexWwUtko2U7Whzg=,iv:6I7c7rbnCq5cSbGRgcQtNgAYs6SLXf5BzaTxIuC3byg=,tag:l9SMFz1R/q3UfqY0ycxE2g==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbEY2MlFPMTZUaktnTjNy
            b0xvNDk4Qm4wSGFLUkFYaUdhQVI2eXlpbVIwCm1UZzBQeWhnSmxhd0xDWE14UFha
            b1Vob2tTVXNGVEI1ZnlwNzIxNGpGSHcKLS0tIGpqeW92R3JJVGp5Vk82YnEyTDVU
            VzB2cWNxYVJ6NS82aGdDRnROU01rUWMKoKk+MjQ7Vpl1ghwra9ajZenynqhW9wGD
            Ol5TwbLKA+7dFBnXuxyaVqTP9O4bxzYTD1++o+P7MO0WxNLaNHLXsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T14:13:44Z"
    mac: ENC[AES256_GCM,data:ZSKwCXmYQRJCwAXNpLjqLeOyQ2G2e+KvTL8+1S1EpvQbNQcYYXvOrYd5goYQx0SU0UA1XRItX1LdnSyRu/lT/R0LisPnBqD6AeR531VrTA9MD9J7FOpEsuW9UKtfo1kMjuU+2G+41G2pZJ/6oI+4KcwqBWiaa/nR3BrE4WR6vnU=,iv:D8uVSYTJI+Cwsr848XnlIRoxqszr/DJ/8v9qe3fDbqU=,tag:B2ShxZaAcGUepyr8zPbqqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
