apiVersion: v1
kind: Secret
metadata:
    name: multi-scrobbler-secret
stringData:
    MALOJA_API_KEY: ENC[AES256_GCM,data:4w8fbuOcqwZtITm1Wo82uxtkvh5NRdIrnlh0YCpYl+iTnWiaDbPPPoy04wJRc/ruCyXBkIF7rGMfUuXRIYA=,iv:bweh4GfngUtxsqyhWSJzaqeN5M2YEb09GKxRs+YTECQ=,tag:B2y+PKxieIQOeS/yiCHH9w==,type:str]
    LASTFM_API_KEY: ENC[AES256_GCM,data:c0H7pi4DAwScSW9K4WI7QLt1ER1jg9Vi7JXtG+0WaOk=,iv:UPI1Q7KhHkclGkxZMw9bDGBoIT1yT/A69v89dOJMff8=,tag:ARnw6yvWwXgzVu9RlY5/dg==,type:str]
    LASTFM_SECRET: ENC[AES256_GCM,data:9z8nJZTOnH4cXZht2X1398vvFnwQPfHC/8SpYiCqXSk=,iv:7Yjnu3bNpB5koNFOmaubFiI3P4x6q9N2aOq1l4otBZE=,tag:+5Xcy334GHqMVYeE4JyZNA==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:ebet5lDmeRV0paN+vcNenx+oijuWYR/Cu0OXiveDbbE=,iv:ZfRmvZdM4CnBytyhYixQD48sPC6Bp7DNrA0F/YRHOTE=,tag:emF4377WKoWIElJiH23mjg==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:EKiLt9eNinBng1ssVcaOB7M68mWYWcK7GhMj3Nj4utI=,iv:/zbZ/R005JX2PDY40HkN/5KixMeLCnt82idLMKXyvtY=,tag:tCMwPv7qRZqQO/W+BVGxnA==,type:str]
    PLEX_TOKEN: ENC[AES256_GCM,data:LHL6MxgEVksO8iQm/3OMREQxe98=,iv:AbxH42B2IaQHIP0Feq2orusMuCLVtRMpmglQfeJOUWg=,tag:B4Ki0tpB73w5+bKShz57yA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMjUrQkRyV3V4cU1Gdk1l
            N09YVUVHNWlxZmVZcDl5aHBMbCtSU3kyVjBZCmVMVCtmRmloQU5DQUhJNytidGpo
            aTJoQ2lBTElleW9jL2VPQUJCZDlZS3MKLS0tIHNCM0V3YnhqTXBqR0tJUk5WaTJX
            MEtmRXY1MkRMZDJSOW1pK1pCMTZZUkkKXOv4Brztj2Ct2GewdqbX6AXk0Z9skroG
            6WUZlwjTUXxf532y41ANBo3CSNDDv9Cb9SoOuQwYTcLd2NsrVfWzhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T13:03:04Z"
    mac: ENC[AES256_GCM,data:b+8Ghc1+M7HODh2/iPJvR1fx9DBBi3ueBZzfu+eErdnl2KtceTTYxKs+8QWp74+J7B6pruxXbjb9QQqVML3g5F8Y8rCCEGzRrcu1ZjMO7s+BNb6oZ3SCW2fS2V6YmRw/0TJcGUuO+P/5/E52+sFugNckWU64P9Qji7u0CQOwIGQ=,iv:3QhC5gzv9DTT7ba8T8c3kQZLG0SndnhE8uPxShCK4dU=,tag:M09t4pfE8UurXpJlyVG9pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
