---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apprise
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      apprise:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/caronc/apprise
              tag: 1.2.1@sha256:127b3834f0679502529397ead8ffeaadf5189019c4c863fa6652e9b942fdccf8
            env:
              TZ: ${TIMEZONE}
              PGID: 1000
              PUID: 1000
              APPRISE_STATEFUL_MODE: "simple"
              APPRISE_WORKER_COUNT: 1
              APPRISE_CONFIG_LOCK: "yes"
              APPRISE_CONFIG_DIR: "/config"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /status
                    port: &port 8080
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
            resources:
              requests:
                cpu: 250m
                memory: 128Mi
              limits:
                cpu: 500m
                memory: 512Mi
    service:
      app:
        controller: apprise
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        className: internal
        hosts:
          - host: apprise.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: apprise
      cross-seed-cfg:
        type: secret
        name: apprise-secret
        globalMounts:
          - path: /config/cross-seed.cfg
            subPath: cross-seed.cfg
            readOnly: true
      cache:
        type: emptyDir
        globalMounts:
          - path: /config/store
