---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

vars:
  KUBERNETES_DIR: '{{.ROOT_DIR}}/kubernetes'
  SCRIPTS_DIR: '{{.ROOT_DIR}}/scripts'
  SOPS_CONFIG_FILE: '{{.ROOT_DIR}}/.sops.yaml'

env:
  KUBECONFIG: '{{.ROOT_DIR}}/kubeconfig'
  SOPS_AGE_KEY_FILE: '{{.ROOT_DIR}}/age.key'

includes:
  bootstrap: .taskfiles/bootstrap
  kubernetes: .taskfiles/kubernetes
  talos: .taskfiles/talos
  user:
    taskfile: .taskfiles/User
    optional: true

tasks:

  default: task --list

  validate:
    desc: Validate Kubernetes manifests with kubeconform
    cmds:
      - task: kubernetes:kubeconform
      - echo "=== Done validating YAML ==="
      - '{{if eq .HOME_SOPS_AGE_KEY_FILE_EXISTS "true"}}echo "WARNING: SOPS Age key found in home directory, this may cause conflicts."{{end}}'
    vars:
      HOME_SOPS_AGE_KEY_FILE_EXISTS:
        sh: test -f ~/.config/sops/age/keys.txt && echo true || echo false
    silent: true
