---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./critical-infrastructure.yaml
  - ./user-high.yaml
  - ./user-medium.yaml
  - ./user-low.yaml
