---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shinkro
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      shinkro:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/varoop/shinkro
              tag: v0.6.4@sha256:19da0fd2df9beb56437b07acc1396286313d4f4039e83c57cdd6accc4e03ffec
            env:
              TZ: ${TIMEZONE}
              # Dummy values, required for first start.
              # Real config values are in the config.toml file.
              SHINKRO_USERNAME: shinkro
              SHINKRO_PASSWORD: shinkro
              PLEX_USERNAME: shinkro
              ANIME_LIBRARIES: Library1,Library2,Library3
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256M
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
          shinkro-mapping:
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.7.1@sha256:c5e1976da735bf0b53979f079a07475d77174c51863cd084e928ff6074480717
            env:
              GITSYNC_REPO: https://github.com/varoOP/shinkro-mapping
              GITSYNC_REF: main
              GITSYNC_PERIOD: 24h
              GITSYNC_ROOT: /shinkro-mapping
              GITSYNC_EXECHOOK_COMMAND: /scripts/copy-mal-files.sh
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
            securityContext: *securityContext
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: shinkro
        ports:
          http:
            port: 7011
    route:
      app:
        hostnames:
          - "shinkro.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https

    persistence:
      config:
        existingClaim: shinkro
      config-toml:
        type: secret
        name: shinkro-secret
        globalMounts:
          - path: /config/config.toml
            subPath: config.toml
            readOnly: true
      shinkro-mapping:
        type: emptyDir
      copy-mal-files-script:
        type: configMap
        name: copy-mal-files-script
        defaultMode: 0775
        globalMounts:
          - path: /scripts/copy-mal-files.sh
            subPath: copy-mal-files.sh
            readOnly: true
      tmp:
        type: emptyDir
