apiVersion: v1
kind: Secret
metadata:
    name: shinkro-secret
stringData:
    config.toml: ENC[AES256_GCM,data:Wcqr2oi32Qg4dRIN1yAO23TZErDalazsInUntTwMlTY6f0qn5oUXi2Ji9I3CKefvGKb+aNaePfR/KdAxvOOgI6j1Lw5C908trLfCAGCLFxOQlbj5JLaBezK9GuuXFxbsxfw4+oIMNzAO1dnU0s1tySztaG4eLcnwSJRFSiVwYZHM+9BrO9RC+9hct0I0U6bqI7aHOzZgmHaQ2ovuZmRv1MeHCol3dT2cM5VFM/feWNZTBK53NSVcDNr0KS0FvQj+hknzKLVHwvJKMP70CAnfs2z5VsKI7u9kKkQtoUWPyiiskvqVqnNdLMZcZYp6F/CYIiwFeaz/1y1rTj3exSiA4CWzDb5YUrOEgCyV1pfOks3Wl4mPwfoLUheXRxxTE6kpxFjCyarVFb4TqVsPSN+hOpDZ80jrZB4g24BdQiJtEc3GNVbp73hvwMxcFJq2C6cgfBFDPJdMNCsjLZLzw3aUi0Adgzy9UJqU5D9tdlZKB6xNvOo6Go1ulJeTf+8i/Y/3UHk=,iv:X21CACzeuSrd9NdS0qaXB1As5nNTPDyK/XbEfH9F5fg=,tag:ivfLZI8pniDrYYn/vm2Vag==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMEFwU0hPbldyZ1JhZE9y
            SFV5QlN3OUlWTnVlQ1RqWGRlY0tBcm1qd1Q0ClVxOVVEaDRjczNtUWs5RmtVWWpw
            WVNmWXF3QS9tS3BjajF5MXhTekhuUUEKLS0tIGFISmNHT01EelN2L2gzSzhoRktv
            UE14RjJ0Mkh3Znh1NUxCVFE1RENpNU0KuSxJxreH1Hi3C+Ia2jsrNFGykgiDQ51F
            HVazfdB6XOmCNzvyNChbWp+anSEeeh1PoHo9zCqk/RGoQ1UHLpEiOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-01T17:39:40Z"
    mac: ENC[AES256_GCM,data:iJ5vNUnQ6iM1axaNTrb85ak5dksVahdMqRLKvlUJRAdtAD/Zyd9e2l9PDn/K5UPcnQI/d/RXksInC0lx0rVeYrXcECbSJDxFZKmUTjA57DE2ORSTqbkU1pEfEQGLpCR/sstlKMMRgoP+LfXyy5ObwvADTcnFc8QNQjY7O5sopFE=,iv:uRXCaql8qBdXdX5QI/EkwPkHHob8QJUR/MyIon0Jqqw=,tag:dy789dcnNrY7QuZprKIwOg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
