---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-minimal-bookworm@sha256:a0915ad91a8963004dcb6972d529b2ea6665ccc2f5f40a016b1a7b4306b7eb1f
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
  storage:
    storageClass: openebs-hostpath
    size: 8Gi
  resources:
    requests:
      memory: 50Mi
      cpu: 20m
  monitoring:
    enablePodMonitor: true
  smartShutdownTimeout: 1
  stopDelay: 301
