---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: sonoff-zigbee-dongle-device
spec:
  rules:
    - # Sonoff Zigbee 3.0 USB Dongle Plus V2
      name: sonoff.zigbee-dongle
      labels:
        sonoff.feature.node.kubernetes.io/zigbee-dongle: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["10c4"] }
            serial: { op: In, value: ["585cda3eca8bee11971703028acbdcd8"] }
