apiVersion: v1
kind: Secret
metadata:
    name: ytdl-sub-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:9PwkehXGdLLO7DSMeqqLUQhgyUPqj1U3hgGs5bm4+fDrr6DuU+kxPR2psDjtk31KO5131l8ZSjO30QgTvVabgtJUTaIpQPZMIY2PQI9u4O/dkdnB+LRqeIM5pUngW1+kDA==,iv:Jtodo5RL1tH6dtrPMDYmBaW/sLZ+FSlkX9JYUM77Ndo=,tag:hGxj/q/RzJlNVJHo+atalA==,type:str]
    subscriptions.yaml: ENC[AES256_GCM,data:fF1i4dnB2CC9w0W7BUWNTklM/ujHnMQ4ocZpr6kTBOpx5mC7f7BcthHJIBns+h9wT2VGvkGpV3xfUzTtmPOfgJKr5N+HLbuFLcwhBD69nXcHC20UveLNDUbZ2YHAh7VXnbk14/LiowHlGCY/F68GpPLY9ncMIrS656KQJMm7wMT9O2V+ERrjP+c9Nu1smq7sVSaAyFOJi8UGMOBTfHku/9lKgSH7y8mwq98uCpTXpYhfpXkZQ6OAtPLucCHiDzI8QgD3wY41HSW3NlkXqvVZzpB0jxTnzB8luC4pRH24C60ceA3cFdEBaD2rqMQ9ohimSpCamwoCNoGUaqfIF0WvR8XcmENe2YQtcZi+a8cW8KTDMXRz7GYzNiuOGxOpG9SoXDtBEAvb2HMtlSfHK//SkWpI6OY8J7ufLi276NwQvV3QbItv7AFBlK6t8nkp2bctESn0AvOrSpO2NAYzP3O4HAq5AAXCDCk8PjWoKLL2RgPmjgfxnA9lQIoYiKSls0sUHMakN1weLTsP5OjK7EVo7os3i5r+CQ2t4KhM,iv:CnkKsmnmjX7gQYhygx++uInoPhG9s8MUMQo8dsqIjEQ=,tag:wXORcU6UABcHaOU9T6b/hw==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByN1FRYXVwR1h5OVdTbStK
            dkVmYzRUVW1wOHlxVUFFSEpXZHVuS1lxZUhrCkg0ZlYzTDA4QjByaUVZMXppWDVY
            N3VGd2htS2diVTRoWDd1WmFia1dBb0kKLS0tIGE5V2EzcDNTaU9ZWU5HaHpWRkVr
            Q3FzOWZYTzNDM2R1b01WaTZOQnEzNkkKThz3toIHv/NGyrz/eP+EhZagBA9dmNQo
            l9b6p7C7UzHhgmnYed3GvSp9fmM5lNWkZcf2JD3CqiJP802AfkZoOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T11:09:13Z"
    mac: ENC[AES256_GCM,data:NNUKQoDWkXQBMrRGIHPIdnlqANWMyX1t6FFpgqgCe3+joWQGBgSoOuXH1KsCC+1hLMXuGgue5/4NLe2HBipSb+zkoznqgS5672KhUVkNXPnnUjxjkUv1XRvPWm6+TokEd4QrorpWQjkV9CEryZ+Xpl92y4FQxtt8LxmvZJ+4dNY=,iv:9L2svhS3PkeXa9rNLvcYPkrBbWzw5zKKGfFnYi/r/qI=,tag:H+flyjdlkhKzCH5XYGXFxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
