apiVersion: v1
kind: Secret
metadata:
    name: ytdl-sub-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:FYgzVv3AySaDVIOt9ZT/Mwb5UUdKGxjNKDxGxqzir2b2k15aSXfwzTaYYUbSC1p0KX7dKlNdxtbrgMFgIO9oo1m+ZcfeCznS9Eq3V+19lwW7Oc6XfBBjva4830qMSKJWeA==,iv:VQGxp5W3BO/KF4/eyxumbS/6KLrAxOuPKTkrGF2Hk0g=,tag:VcfpJW2wqioT2VeBZAElJg==,type:str]
    subscriptions.yaml: ENC[AES256_GCM,data:fdjovG8fy0OGBD3FLvFpadNqze9cx/y2VbBZFAvzUoCe8W0v43sKJQRx1nwmGPl+2k8fwnxgvGAwjgbblNTxbNtF7c8axr0AlhTv2hBBNh6G/jhRl+vDwftP9bq0bYaTeQ0IBklfxbGOBcUdTLHYDUytKuk2QEVQv+z7VRwxd28xeP++e22/VKXU4WJaHEjupR5goybaj2CtJ4D3lF2G6kaDtWG8Iq4WDa8I1fjfgzRrJx830ea6FAiuA+aIkuA7jXvOOD1cHEzWJe2BdRgkna8AZR3+29rZy1JAogwz+VisHFUofasMnwpn+FcP/96oVLF6JljC/y7OTlEbVH7pTofBSlVyGdqtmi0M/5NXyOfocV7nESneY6rhRgggYSbo0C6MHKDMAg9AvJ+nP17sGjedtEIWTIZUYpTpJyHiPSKc5BEMv4Tan6txhJXYxUJnUgrIH2n99QJ3nmxWLjBgCSJPzA+20HPX,iv:eZccoB+pHM1XzjDMNbjBCef8SAzkeLFBD4yYoRfmyYY=,tag:ZhN8spYTLQd5sUL19wiycg==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvblEwNUY3aHlma3lVQUhQ
            NlV4U2dqSFJRZ2UzRlVQMVNCS0JjMFNQY0gwCitiZFIzRTQvcVhqR0U4aXdKOGNY
            SjFuSFlFNGc2TDUrUVZuOFpuTHlJUUUKLS0tIE1zM1NNT096WHlXK2V1SGw0RXJF
            ckl3WjNxemxYdms5Zi9YMCs0MC9rYUkKRgb7vKroWdPLpUesV2KHiwRUvhfHoWsp
            8Xb+LEECNzpwZF/FkXVJBlvC5c6HApfAZv7k9kADzuV4EtFyjyjDyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T10:44:25Z"
    mac: ENC[AES256_GCM,data:rfaN/s1LydskS0wOHBAEKA9i8E68O3U0jL3Tawjf0p73xqfHilqzUtJge+U8CdmEOvwkkhvD5HGYJ/hPAwYcMzP7rgYfutHPOt5lwOC2k8drtsx0hfe9iGwMsmgziV5n6loN/qwdr2MQkUeR/N4Dcy9gAynqTIqzqo5jvTh0TTI=,iv:ZY2Cwpy1utmagT8qjKxxeCjIiqJLM+BrkQOlGb6Oo6s=,tag:26Okre6kFcs5QZSe8miJVw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
