apiVersion: v1
kind: Secret
metadata:
    name: ytdl-sub-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:uauop17MyuYQLs5hw6u589s2MG0vT/6bjsRHYnGyly69Kxdd1RZoJxP0G4zuMtVds+50GpKv5N6dwhNvt6CRpU4EtOYwOxc3I1RppI6Awkgbjn9BpzmjQ2CvLexM5z2Ozg==,iv:vNCOTPKJR3i7cGOMRz0GH+gVR9+WO9wXTsXI2ESxGh0=,tag:K4FTzWbU0ynXlo4JQi475Q==,type:str]
    subscriptions.yaml: ENC[AES256_GCM,data:O7j1821usTgxo47B3oFRxwNoe7+iZZyd+arjvlG/DvJHZx20DSTk9+FiBVgwxftHctDFV/1h+/gu8nCBXP5+M05TvOLJou3JFL+lOYdSKoWwjdJAHbmViB5Dze8EvPOzdpjNCiTN4DvkNNeEFYcCZMimr8cCJ92OVvp25/M5E++8KqFmYBKa3CoNz2G+TlBfYjnsJTsC7opEdHw6IkcsfszAKa9Q2gi/DbGpsR2VcQac+l1p0t4ejFZcwAHGN+ZgZ1k2x/BiblO7wJ9entgR9DR6TXie7PEtZHDuaMFbTBAnoTO2yCylcSmy5wUOWvnuuQoSnOE3b1XMOnqcfFzXl0CZxBz2D0RIaZnv/DcyYAuY5KOM6jXzw2YApz9DRj91TEmFF8Mu7/7l07GqYE0TQ7kFq+FqwiRFH/7NxEjRk4M7krGThfKwWKpnc8M2nRQkB/LqabKUorI91XtduPuhAL2uiqsgZh7Jp5W58yBtVKyTtBOhvioTZpRExrXfA4FPtPYreszn7dW4Dfh+HcpV,iv:nAcKfKCazNzhWSU6jAbh4WLqrlfj0R63zxJ1WfDoTBU=,tag:wcZOPdmOTzJFKls1jzgV1Q==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTC9KUlRNMnp2Zm1BUmxV
            REI0eHpEUE9wQ3hoSDFlQ3A3U3pRSmdyUlZVCjNUUkpoVDA0VGViUk1UQ3h1djZK
            Njh1M0Fjb3pjV1RmYmIvTXUvOFdoNG8KLS0tIGV1ZEZYQWZYZnA1UzFuQjN6SDlB
            K1lNYm9qRG8yb1pSOHp5M09CS3hIclUKNPusfrSSsocxzFWMcL8asICWy3T1UAL5
            x0xNeVpaVkauFGbuJgqpU2WNVhz9RoEvItV4YzN3E9y75hGWqNNvGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-14T10:48:25Z"
    mac: ENC[AES256_GCM,data:0PPANOWON36eR4SK+7eMQwpymsG6yE6LTxXf8bRYMVorctg/TtRvRpDaeVJcamP/3AuFQeSTXDJw5qdXDnavFhn4qHx23lzyZ+c91We8GLm4dtNWf68HmIB/UB6BUXtXVfW/4JfH29dIupDEc6rckHEZ9Qs2uZX/yQ+OusJr8sA=,iv:t/lkpealYvUZPuobyBPhpl+fapucNHVXQUYLlWqtTsU=,tag:MgccD45RgE0FLwP2JEaPtQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
