---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: immich
      version: 0.10.0
      sourceRef:
        kind: HelmRepository
        name: immich-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            env:
              TZ: ${TIMEZONE}
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-app
                    key: dbname
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-app
                    key: host
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-superuser
                    key: user
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-superuser
                    key: password
              DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: immich-db-app
                    key: port

            image:
              # renovate: datasource=github-releases depName=immich-app/immich
              tag: v1.144.1

    valkey:
      enabled: true

    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-nfs

    # Immich components

    server:
      controllers:
        main:
          containers:
            main:
              resources:
                requests:
                  cpu: 1500m
                  memory: 2048M
      ingress:
        main:
          enabled: true
          ingressClassName: internal
          annotations:
            external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
            # proxy-body-size is set to 0 to remove the body limit on file uploads
            nginx.ingress.kubernetes.io/proxy-body-size: "0"
            gethomepage.dev/enabled: "true"
            gethomepage.dev/group: Services
            gethomepage.dev/icon: sh-immich.svg
            gethomepage.dev/name: Immich
            gethomepage.dev/pod-selector: app.kubernetes.io/instance=immich
            gethomepage.dev/widget.type: "immich"
            gethomepage.dev/widget.url: "http://immich-server.default.svc:2283"
            gethomepage.dev/widget.key: ${SECRET_HOMEPAGE_VAR_IMMICH_API_TOKEN}
            gethomepage.dev/widget.version: "2"
          hosts:
            - host: "photos.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix

    machine-learning:
      controllers:
        main:
          strategy: Recreate
          containers:
            main:
              resources:
                requests:
                  cpu: 500m
                  memory: 4096M
      persistence:
        cache:
          type: persistentVolumeClaim
          existingClaim: immich-machine-learning-cache
