apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
data:
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID:
        - ENC[AES256_GCM,data:gxU=,iv:vsdoRxrjoyUIghLPPBt/rdH/tH9+RF/uL1Kp77+5J6Y=,tag:qWvPyBRCUXiA3SVUkJzgdg==,type:int]
        - ENC[AES256_GCM,data:OG0=,iv:0IaFzmrgGSkkKx0D3blyn7YCBzUR87nbft9SPoJAots=,tag:+CcWQGJWDE2fLGOVClUzxA==,type:int]
        - ENC[AES256_GCM,data:tqeU,iv:wdIecbVRi4Ispo3tSLnCOdhrBDnxQgY5xaKltXjtP8Y=,tag:feRfVXyFJ+C3Km/7+GNgrQ==,type:int]
        - ENC[AES256_GCM,data:Mlya,iv:s4wfn8Op7R7q7eiXUTnoXSIghwONMltfzyauExnvsAs=,tag:7jzxRvE+RfANpPrmzjqIdw==,type:int]
        - ENC[AES256_GCM,data:TQ==,iv:mIFSUO7FarsbEFUC2ZJ4y3BT/y4UeAUuK4yp0TrLIAQ=,tag:NzHm5vdaKNxQZC7zbFgDOw==,type:int]
        - ENC[AES256_GCM,data:EgU=,iv:9IU9B8OB1nf7AOa0wEbeSXcMVeF4tTwNdFIJk76tqWw=,tag:XPDJP3b2X23AudB95seTYw==,type:int]
        - ENC[AES256_GCM,data:t8c=,iv:qYQ2fxCBLLzVGop3wPHdrXfJqry8zlywPBbbItzusTc=,tag:IuIxEJCCXtGJSd63nA13PQ==,type:int]
        - ENC[AES256_GCM,data:hEKh,iv:+wSRFZQYvmqOS0Jg4Wh0yHWwbHgHLDf2mFYD9ARGIzk=,tag:+wd9FwwIbNL/ji+un7xyXw==,type:int]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:zxm1Ag==,iv:HMx6jFEmMlME4f9AHuU6J5kzonb/iT/2Ank8uuSdsQE=,tag:NV3qVz1CIHiFXhNFKkHViw==,type:int]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY:
        - ENC[AES256_GCM,data:bqc90RSCkm1o0K8O7UatyJfLfp06c1KtCtTMnUZdoF4Oz6nps+bandpvksWpcYko+Q==,iv:wSgyQDpfqYLpnBvGt144S+zMUFiabeWjvV9so/0kz7g=,tag:ph90SYrBGxParmUG1t65Cw==,type:comment]
        - ENC[AES256_GCM,data:UzKI,iv:rgqTfeWZ4OdAxAptIdITX60jf1BFU2rsvQEd0CPwC+0=,tag:eqz1vQ10ogdWOsWSdh3nPw==,type:int]
        - ENC[AES256_GCM,data:1PA=,iv:0twtEwi78ALPBQroJuRD+UrwwZGn+G2shzKcE5iaMbM=,tag:wBf5TnVpeyZph2xNBT6hew==,type:int]
        - ENC[AES256_GCM,data:pIM=,iv:TEyS7c7t+pEEKD9s0N6Q/eniRnhtT3iBW7Y4lnCJEjk=,tag:LIhfsquyPyQmsmEZaUvMLg==,type:int]
        - ENC[AES256_GCM,data:i1M=,iv:ij2kiSgekslRIBp1Rr0DDn9dfE+sKCJhoFe4BHf1Emg=,tag:wuAkAVhKZOEbPai64IALDA==,type:int]
        - ENC[AES256_GCM,data:kWzl,iv:vAOI8ybkTRc8/f+6ubBQLdWStzPxEXjyTasdXzVEQXE=,tag:6lY+vvul30+Bg1SXWtFxrQ==,type:int]
        - ENC[AES256_GCM,data:uA==,iv:uJ1/M328GMN+aiPVG8pZq3oiwaAgGoAKrv+OAJ7f5YE=,tag:b64LbpDBN9t+Tra+eFIB8A==,type:int]
        - ENC[AES256_GCM,data:BQiC,iv:OCupwzm1gGSD/6QKigfcIDXdO0ZxdkoympaLmMS6CYQ=,tag:SI5lO13s3pW/IiKqZCQYbw==,type:int]
        - ENC[AES256_GCM,data:Zxg=,iv:Wa/slhK0kqOcecS8GhD7yW0oWOHIjSeEaFq4E40Uom4=,tag:R39ipBKHWHwqLIohlSmwEw==,type:int]
        - ENC[AES256_GCM,data:8Bg=,iv:lArnBA4m5/82SPZvmyxgOzoD4ZkMfQdMReCF13BmEQY=,tag:vavSgT+rfducFmeqaFzh+w==,type:int]
        - ENC[AES256_GCM,data:7f2I,iv:pNjD68UoSvT+t8pH7SLiM63YD6Ga+drG2IjdJBDLdmA=,tag:6h4v382pgUuiIPQOwFHJOA==,type:int]
        - ENC[AES256_GCM,data:8LD0,iv:BKLWKjLZoc0h/9Cxq87CKeuXGx94UQWYs683GFUIDFw=,tag:ZdzPajrZQnDS4BX4dzjkFw==,type:int]
        - ENC[AES256_GCM,data:BXU=,iv:WKOWBHwXU4xLn6vTQTzVd5rEXnpbO2oxa6RPm9akPhg=,tag:XucVFaBsjSvwqLsRPLStww==,type:int]
        - ENC[AES256_GCM,data:gFM=,iv:N2SPidsBwMSOlBxBFmmhBdVYRwgS3Wqrc8baVqCD2hk=,tag:GNtaSddE/izdll+3T6VYkA==,type:int]
        - ENC[AES256_GCM,data:O0I=,iv:IIK861G9LJ1vcDLWr5iT5nNgPEXWwykZY6g0RTfJYjo=,tag:TBGC5kDcO225TkoQv+VOEw==,type:int]
        - ENC[AES256_GCM,data:dw==,iv:DaomtN+igWXVWXS1JjrqUrRKhKuHeQKw/UQq5mI2G9k=,tag:nAPdfgEcE7eVCVzBxdtGAg==,type:int]
        - ENC[AES256_GCM,data:DYY=,iv:fwhZ0URjqdPEwsioRDDsrtDSd92a3BIAZJ/Z7t5jrOc=,tag:oT8eJ096FXK8u/Ob/u8B4Q==,type:int]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:P7PXZyWBSivhtp2a8E49,iv:+NSIgYBuuM1JOfCDkYoNQ+8Hu0AXs+x+P+C6vzgsY4k=,tag:Uv72lgJjUlGCwMHvWmFRtQ==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:7qz/G8v9fKyLS5jZH87UjEy1r4U2gCIG+tTe/FDNhjJGbQ==,iv:l5ZPJOWFtvWC3UvvnHUoAmlPKj9iV5RgTLy+8l1wqPk=,tag:9DYgUrGsiMVQt2twxnotog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Zzl0T3ZnQ0orclRvTEQy
            N0krQnY5eXhHY3c4TVh5Sk9PVWMvYWNqaEc0CmovZ2JkaG05cGdORjV2cGtFSGhr
            dUhRd0dLSmRlMzBocENDOUdLck9XeE0KLS0tICtJaFRqcUZvSC9VQmV0RE45MFhV
            NFFxWWZDc1pVQitzMXdabGpGblB6SzQKDa8Zo6Vk4Ld5c3B8Qtvf8cfV6k+YOTQF
            BQUNka8FbUYXC/cQ41RjLL+S05KMGGWK93UAb79WxBoqYLn9AYjXLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-04T15:18:28Z"
    mac: ENC[AES256_GCM,data:thCwSdZ5aQyDkLnIpH+AOXfEZPR++3GfrGe20xszmmdLzaY6M7rayQBapOr2TnV3rkSt2OonvG3qvjxdzidJcm334Tpd/L6uPWdAwGn4SE8NVDsLyxqj66DbTvfLDcdo6wE4BB06dhqq+hAWPnqejek2z7T3J5D1WIbxADvHXTM=,iv:di27YXw8NMeRcz+/9ACTfIoJTluNbOyKIgBeSEWqxq4=,tag:ED8p8xaX9l+sExRubbhnoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
