---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: 23.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    wordpressScheme: https
    existingSecret: wordpress-credentials
    wordpressExtraConfigContent: |
      @ini_set( 'post_max_size', '128M');
      @ini_set( 'memory_limit', '256M' );
    resources:
      limits: {}
      requests:
        memory: 512Mi
        cpu: 300m
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
      ingressClassName: internal
      hostname: wordpress.${SECRET_DOMAIN}
      path: /
    mariadb:
      auth:
        rootPassword: ""
        password: ""
