apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner
stringData:
    RUNNER_SECRET: ENC[AES256_GCM,data:ozpb6zDuNOWP+ahKDblHNkrt7SYjPAvzR+wFmmPPkij2SfO4WBd29A==,iv:PjhRDVZTCLvEVzdCCRh8h1EACpuCWu09IIyeqoGTe5E=,tag:ilsfQK1vxkCivlo3U9iM5w==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQkdHV21lTTNqVDJYeEpZ
            RDNKQ2tjUktpZFRKaUhMUjh1UUUwajFuK0dzCm5BUlRBbXVpYTdXenhBS1ZacWdE
            d09aWjFVc1VGcGxTeDJLTDV6WFgyNXMKLS0tIG5pT2hzMDhtMzNEZ1VuNDFXWENC
            T3ZjbzJOTzhEcitnemdXdlRuTlRadFkKtpFdfEDGba/NNzYd51Pvgr3jHxW/2oJm
            Yfne9BAUTNjkllhLSl1svwkBmG1cBH7bnD3mwV+NrYnpXfl1gzUseg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-06T09:41:36Z"
    mac: ENC[AES256_GCM,data:L8lJqViRNeteJ9WjEAktlyGo0Ee9xFtFffuS9ZFokWRGnTRFQFDDg9xRHNm/9TJfcW1oAHRQc1YtZQAaSGvCvuNCqOHWF7+2jdEyLliCYpGA0A0npsy/qK6NqQfqmpak3xhN74/ikrDTUCvno8v/WwOBWGi1TLfotjrO2OZSVz8=,iv:qVi/bjMndZ9ujZxCegdfkCk/T/34Ncjl0wvZozmZIFg=,tag:abo2K41LZOQonPZhsCGBmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
