apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-media-downloader-secret
stringData:
    LINKWARDEN_TOKEN: ENC[AES256_GCM,data:+uGfMkUQGPzS5ZwYG3pGR/f+XMEhlAGnaiPfp0s3RXzHyMl2zUTl3NtHu5bZ+HT1cmoceVmm/fk6xgk8JzYhSBWJj/FfZSUjrJ4Kdw2sZ9fPsDdITMv4HdJIL6xOcC0EfXQcnr5GSrW1fVfdPHNYfJzCNmVlcknRagiZBxy7gkCdtj2wOElPNHEIUy6i0PR/NryHDbuYQUxaTKU3uh6z9x9fyng/p7up38xDt0EO4vZU0tAlR4WtM0hLDFhbeDB5dsd4fB4=,iv:KMs041NGSzTbJBZ2He2HYZLRbhOKWreUbZr77egzrI4=,tag:e4l2pLybO5Fz76g1UmwaHQ==,type:str]
    LINKWARDEN_COLLECTION: ENC[AES256_GCM,data:9m+exggLuNES0+MHf7FN,iv:VY3OXfMxaDaweoq9MgpUw675H8p+bEwgB3w5fMbiUZU=,tag:KXybFubbcwPsXBIUpkN+BA==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORExGZkFEY29OL1JJM2ly
            cDBLaG1rWjUwNXFFaWNUTjQ0TWtxOFk3V3lzCkxoeVo5L3BJeGlaTG9WTnhja256
            dmdrV0srZVVnTkZCYStDeHZCck1zaVUKLS0tIDdSc2I4RTZOanhxWi8vcEZXY3dX
            aDVqcURDb1l4dGo4ejlvKzI4cWVrUDgK37tVx0WPTLgubsuFOsTYddriGUG+j32x
            9g95IBeNWh+i3pw7IEwIQvqQPIm0Wa9wsXlsFzmdLOrlOBgph6bygQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T09:08:05Z"
    mac: ENC[AES256_GCM,data:/2u+XQDXX5DqbcJvPNdA6zTeBY/MDKKUOK6wOHHDY3kwIML5LQicMNIMqDjfPbUaDz2aC+e/tsuMrqkTH8siKHEL61jL6UKfwTlzwErYQKjVbV3QshXlVXdLhsF9IGBvU37TG4NaQlgpHpYND9k4mlWfsEiPWgERf75FG18S1qg=,iv:oqSqlXcPGEnGpllVl9xxR1+vGbq81FTsPCsA401dXTo=,tag:8JH9+eMRci6OmMijksp+vg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
