apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:qgtHzOpK8CMrQIRVJ9H+lu/FuyBbH/fNTf0l6GlRp87Ac+3uScsaMA==,iv:5UFQlFjRTe8Sa57ThnAYD4aRcTJE/8UWIj35HNlRE+c=,tag:pqxpWz0T+yjQZ6+fkZdsZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbmxySUx0WS9TREU1WmJL
            YU01MEs2R01EOXBZTzZsaWkwbERGZjYyczJrCi9naVp6ZER1c3RWYm90QVgxZDJP
            bGtSbDJ2aVZ2NEdIN1hFQ0h0dVpyYWcKLS0tIHFyTzJhWEhOQWFLOEsyR1g0aFM2
            ZmJQVVB2cEYwUzh2cU8rMmlYOEhwMFEK/baY96lGJP+t7ZCbysf7Lt3ZnbfowKGH
            pc8Az3l/hVL/X+ySc97dmzP6kyzxDTdjn23rZCbDDGpx5EYIW2Q3KQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T16:25:58Z"
    mac: ENC[AES256_GCM,data:8As6HlNHUVoNyOiXZfDN5T0U+oj+SaMh8P6fjgZtLl27moPEi+EWHilySw3XGWzGLIicAY7Ted6qpRMU+2fbAQPbk01TTquTxfVJvK8/xXZ4QhARSqKXq0IOWPgSlbja7jHNpjKhV5zBzTsLNGLfqrkJQvgikSGtAJwjjmPhmwc=,iv:b5EPxzJWZuCjMoAlSBgslsoau2WL3+OBkdoItsN5AVA=,tag:lWRsVFyV1o4eUGLid2LAJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
