---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      bazarr-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.3.0
            args:
              - bazarr
              - --enable-additional-metrics
              - --enable-unknown-queue-items
            env:
              PORT: &port 9707
              URL: http://bazarr.default:6767
              API_KEY:
                secretKeyRef:
                  name: bazarr-exporter-secret
                  key: API_KEY
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: *port
                  failureThreshold: 5
                  periodSeconds: 10
              readiness: *probes
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      main:
        controller: bazarr-exporter
        ports:
          http:
            port: *port
    serviceMonitor:
      main:
        enabled: true
        serviceName: bazarr-exporter
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 5m
            scrapeTimeout: 1m
