apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: storage
spec:
  interval: 1h
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.22.0
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: cloudnative-pg
      interval: 1h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
