kind: Service
apiVersion: v1
metadata:
  name: ak-outpost-authentik-embedded-outpost
  namespace: default
spec:
  type: ExternalName
  externalName: ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local
