---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./filebrowser/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./home-assistant/ks.yaml
  - ./qbittorrent/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./actual/ks.yaml
  - ./immich/ks.yaml
  - ./mealie/ks.yaml
  - ./paperless/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./overseerr/ks.yaml
  - ./homepage/ks.yaml
  - ./maloja/ks.yaml
  - ./multiscrobbler/ks.yaml
  - ./bazarr/ks.yaml
