apiVersion: v1
kind: Secret
metadata:
    name: blackbox-exporter-config
stringData:
    blackbox.yaml: ENC[AES256_GCM,data:j2PBCDISenTgqttPH1hg3rtvxzZ6ZfEmfhWjUK+DmkA3gjor6U3NaTLrHL8jV1Wzwr/u1dZj5E0+tHXoUwuq1mFd4A180Hzq5up1ml504qfRdchhp0cELKs/qk7qqfK1YhRYsP0M89y05xgaEn5CCz4EMPzGQWuWqlmreCJJLTE6f43xiZ7/uxW0wbWZzsUYt6hHExbj6y/Umns3rLLrjto9IT+H66GufivvVU8LMWBb4712PGFAZsbI/D9XTimyTd6JQCYdWJF9N9Jy/4GMVYmG3JFOY74uyEbczZcgpnOYWzBgm9YFNLwJ+lJN8IHo9l/FrrdACqmarb/+Iq0lNH6QqVQVfqoT8yN99Bnlmi1PACNlkD9xxahq2Ha1+EFKlaXUtxG6LDHsGwNaumaZJYdhip4ltDuBmW6j3MgdYzAoJ56j/ryBPO4HFJUr3/+g2+Ayid0I+mPU3Uan+Uy2aycbq2BklbsUlnOe001T4+BTFbnAsabIch+Ca3RhFdi7yYBcMujsCSamh70EstX/92enJFPUTG4tXmrRpdsMoKWz2CAqIff9Rp/KRnIfcrNeZNKJULBNTlk3BIroc1WTFWE05QezvTJFzBuw66KhKMHEWJgJ9Xny/RU9tG5Xf8juK8aBvb36H0OALuWzcljceBRoJOdVHSEdrq5ma/EAT0cQVVuUSfwD28qTU5KT7Q68BzGMlK5W0s0KhE72IbhXsg3GI9mhHg==,iv:h9pSCHcNIhKBQl2na7K6cOk+v9bl9YCZYDQbfyTUU70=,tag:UgZ/dRL3HLqBs6SrhBdOAw==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRWhqMm44WkFReW5Sb2Zy
            ZGN2YnpzYng0UEZnWVF3OElaVDZLNGNqdkVJCms1MVlRQmhITkQ3TnFOckR4OHNP
            UVcxWGNkWkIzY0l4NTVzUUpoNmt3L28KLS0tIGttOEExeEVtSGR6SUVFWXNidlYz
            WTkzaVE3Q25ROS8zNFFBSCs0SXBDMlUK5JWu0bv+JJF/w3TZ+qFGNQdiTt4APSBr
            t3Scf6exK4/YVdP0nwnEIVOBSNSG9/uiXR+qAz5aLday7QzEeqPhoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-30T12:15:17Z"
    mac: ENC[AES256_GCM,data:DG3v0jmLyhsN6OgDNI+eVGjqb/P7OHIg0ir5REoNIuFjNMqls0nJ2yp6QNRqgsCkSqAKMwV4JJ9HRbZcRwfvm6HSovTLzL67dN6nZTHm4xKNz/Aih7OsETqX2wT9zTPS1FI2n0jkizfCAnnvZQTAbaRSJskQtz1hD/4k6MK5WVE=,iv:82rQezy1VKWh0QBusTPGJ8Oy7thAvoP6XknZg0JQfJQ=,tag:FJdXqp/v+i4f6qbNu9dgNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
