apiVersion: v1
kind: Secret
metadata:
    name: blackbox-exporter-config
stringData:
    blackbox.yaml: ENC[AES256_GCM,data:fjHZfm60UUymxjYod0flocaW+XP0BbkbG6nMJva+LwB5VnCtkKdpobIXdtzx6nNav4t66y2UySF/RNtE8YZG9ekz9zLd518cbhSCg5PuCu9IynICvrRfKSOmq4t6ayEHn9QgoaEU4Fm9j49GsLr0TsWymltTZb5wzIu3ljk6OyuKlsjC0COrm2Rl10NCrKx4MNfizC9EcYD5mFNVECY57iNRC6Tl/2h/av88oPvsWqhJlYwJBrEij0qis9eXxrT/gF8NwMRFReYbp3IwQa3xoz+k0MZdgNhD3oyDnnvOdB/eE06RSQz13dfuAZt2Th74z6hFmIL3yzpSc2qc23QLMyGkxvfeAVQ6ctD2OIArLhxdsGPmtXP2wH/bG/iSnh71ePylM2yXz1rNYf0fEmw=,iv:d/W1rMOYNEqd1wlDoh6y2D+jsTLrLVf/KRi4KhS/GyU=,tag:hUv13fR6xrh84Qp4xHtnBA==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRWhqMm44WkFReW5Sb2Zy
            ZGN2YnpzYng0UEZnWVF3OElaVDZLNGNqdkVJCms1MVlRQmhITkQ3TnFOckR4OHNP
            UVcxWGNkWkIzY0l4NTVzUUpoNmt3L28KLS0tIGttOEExeEVtSGR6SUVFWXNidlYz
            WTkzaVE3Q25ROS8zNFFBSCs0SXBDMlUK5JWu0bv+JJF/w3TZ+qFGNQdiTt4APSBr
            t3Scf6exK4/YVdP0nwnEIVOBSNSG9/uiXR+qAz5aLday7QzEeqPhoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-05T15:46:00Z"
    mac: ENC[AES256_GCM,data:Rn4J8+obUsoHTSdprCCaLbaRoqyzD40hQYR+frUNn+D04DQuYsUfls+jPd5IX8D444m2Ce1e3d0fvgCPJfwEptjLHM1rChp2GbKVRLD7dSF/c8jCPSydCTERpbewoy9qjlGv8hCjTQ0p2oTrQhKTGJp8fMj8z8PQcda/yS6/IPw=,iv:Bq7W0lgulOSuuBimnBF1lALNEK5thd6EBSxg2UgVt48=,tag:Bt4LWJ1RCq+Gj9OcnemgSg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
