apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
stringData:
    username: ENC[AES256_GCM,data:XmS95lI6,iv:/HQ5pbhwyl7c13ZGZTZGC2T/Sz175KHRs1fxK/VAG6A=,tag:kiwy44NfLshLuunRQKZP+Q==,type:str]
    password: ENC[AES256_GCM,data:JIO/1BFdvVFlCBbIvLyrD8uD3NoeqTvulE7al6+hDNvcxGRy0I1ra+yYvWxM,iv:Hnztjoq6R714yrhgIOfjJCmG1Ed4UwMZpMx8diYOwlM=,tag:I6F1Fj1yhc+avoUH96pNvQ==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRWZ3ZnVBQnlqcis5Um9Y
            V1Zwa0R0N2VJZUtIZnZWMjROR3BXczN3RFFBCm85MlJGeWlaVDBjbzA0bjdRVDRo
            bFVkSERKY0duTnhpRzRUbHBTQjJ0YWsKLS0tIGFibXNZbENkbEJHcHk5Mll1ZitK
            WHY1VnNYRkZvZHJSN1F3NnBhU05HcmMKCDZr4O0idx/lls/r29oViCbRnwa4bqvL
            qp3WslGjKdPd7MumUHfrAKQuNJEnS6wuiepr3930FwhseQETSMuTNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T08:12:49Z"
    mac: ENC[AES256_GCM,data:Mo/DqNeo4bfknOLYMot2M5lC9/8D7tV4mIr+DXyS2X9UR1RJ+4CofSQc32w2fPmjx4VPLSiB62Y0WJhJjOY9sJxBbFOeOVChsAegBXA4eaw0TQu2jHtPM4ovz0nVyatti3dn2354iBX6CDx1tgFk4ALD4U+rb4W2yVXej2sgpgE=,iv:FmOMS7ZR4lrEAfXMfmGNxuqAwMC/+wBuGp7h6IpKd+I=,tag:EzOjTl6aoe8wuPqu4xgLRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
