---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seafile
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }

    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          mariadb:
            image:
              repository: mariadb
              tag: 10.11
            env:
              MARIADB_AUTO_UPGRADE: true
              MARIADB_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: &secret seafile-secret
                    key: DB_ROOT_PASSWD
            ports:
              - containerPort: &mariadb-port 3306

          memcached:
            image:
              repository: memcached
              tag: 1.6.18
            args: ["-m", "256"]
            ports:
              - containerPort: &memcached-port 11211

          seafile:
            image:
              repository: docker.seadrive.org/seafileltd/seafile-mc
              tag: 11.0.12
            env:
              - name: DB_HOST
                value: "mariadb"
              - name: TIME_ZONE
                value: ${TIMEZONE}
              - name: SEAFILE_SERVER_LETSENCRYPT
                value: "false"
              - name: SEAFILE_SERVER_HOSTNAME
                value: &hostname files.${SECRET_DOMAIN}
            envFrom:
              - secretRef:
                  name: *secret
            ports:
              - containerPort: &seafile-port 80
            # - containerPort: 443
            #   name:  seafile-secure

    service:
      mariadb:
        controller: main
        ports:
          db:
            protocol: TCP
            port: *mariadb-port
            targetPort: *mariadb-port

      memcached:
        controller: main
        ports:
          cache:
            protocol: TCP
            port: *memcached-port
            targetPort: *memcached-port

      seafile:
        controller: main
        type: LoadBalancer
        ports:
          http:
            protocol: TCP
            port: *seafile-port
            targetPort: *seafile-port

    ingress:
      seafile:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        className: internal
        hosts:
          - host: *hostname
            paths:
              - path: /
                service:
                  identifier: seafile
                  port: http

    persistence:
      mariadb-data:
        existingClaim: seafile-db-v1
        advancedMounts:
          main:
            mariadb:
              - path: /var/lib/mysql
      shared:
        enabled: true
        type: nfs
        server: ${SECRET_NAS_IP}
        path: /volume1/drive
        globalMounts:
          - path: /shared
