apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: seafile-data
  name: seafile-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: "nas-drive-nfs"
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas-drive-nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/volume1/drive"
    server: ${SECRET_NAS_IP}
    readOnly: false
