apiVersion: v1
kind: Secret
metadata:
    name: seafile-secret
stringData:
    SEAFILE_ADMIN_EMAIL: ENC[AES256_GCM,data:9Rw2mO7SqQJVjU5oEGNvT9w2b+iStVpgkg==,iv:rjl/99L2m+OLUDIWq/vos0FZTKJZuJhiZp6czysM5Ls=,tag:HZM8kaV/88q2kqv6+C4wZQ==,type:str]
    SEAFILE_ADMIN_PASSWORD: ENC[AES256_GCM,data:zfs1tW83XkZRsm5HeqCvDIqprD+ivW2vPfokxVgHow==,iv:StQCNgXDbc1xUrq7tzs9gAEXE9LtUNAC4xvb0VGZERU=,tag:p00lO3T00yuXfCaZqtDC0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVkxCK0F4bzVKOHc5NjZk
            blB2SS9mWkp4SjU0ZjNRbmhjOUYzT3NYTFhvCkVhcW9ZVlFUSCs2SlZBLzBnZzRT
            Wi91c1o5MUpXUDdLMFhXbDNyWUVUTXcKLS0tIERXS2pLWUJ6cmpjVnB3YStkTjJE
            NnkzUzNtdlE5aDlXdCs4cWVzbzZSbkEK1B6eJoEipofjBBfRMFtUJZ+w+clL96GI
            LhW3jPXsMnbqQqgsxk9goEawSx8PmSCzvL7OIMJKR2rDp6mp4SaCVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-01T08:49:27Z"
    mac: ENC[AES256_GCM,data:uGKygmw2mirsuDhY5R9daIwal++F5vIGw30pwKD+Rj1MR+DtAT+v//nRHmAsWuRdX/dlchH4QAwgVD9ltjEOekk74x7pIqmbB2DUmzXlaaftIrWgc0tHK4fr0opo2rXG29kNuy/OdfCmIqNf/6xfqL3mSxhnXgR8+gYnyemBaFU=,iv:SjwNuTjurOo20Gy5fMkA9MQKZFD1+wul/oCphDn0hdc=,tag:X/PL05CTPDZaBx0Q+o7Xqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
