---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sonarr
spec:
  groups:
    - name: Sonarr
      rules:
        - alert: ExportarrAbsent
          annotations:
            description: |
              Exportarr instance for Sonarr has disappeared from Prometheus service discovery.
            summary: Exportarr instance for Sonarr is down.
          expr: absent(up{job=~".*sonarr-exporter.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: SonarrDown
          annotations:
            description: |
              Arr Application sonarr in namespace {{ $labels.namespace }} is not reporting status check correctly.
            summary: sonarr is Down
          expr: sonarr_system_status{job=~".*sonarr-exporter.*"} != 1
          for: 15m
          labels:
            severity: critical
        - alert: SonarrUnhealthy
          annotations:
            description: |
              Arr Application sonarr is having issues with {{ $labels.source }} health check - {{ $labels.message }}.
              For more infromation check {{ $labels.wikiurl }}.
            summary: sonarr is unhealthy
          expr: max_over_time(sonarr_system_health_issues{job=~".*sonarr-exporter.*",source!="UpdateCheck",source!="IndexerLongTermStatusCheck"}[1h]) == 1
          for: 2h
          labels:
            severity: warning
