apiVersion: v1
kind: Secret
metadata:
    name: sonarr-exporter-secret
stringData:
    API_KEY: ENC[AES256_GCM,data:69Rag6ese9KE49tKdgIGzwhzOEbS9qYhEGPUKs1nRlI=,iv:xPant7aFzz7X0ESErtKDLlXdRZmexBKeNqJ9YgbFPsg=,tag:tTmie2Xv47ZhUG4yIYOxBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMb2xKbzVsSWhiU0dmYlpC
            S284ZDI0UGJlNlZ0M1hZZklKV2lVemt5QVF3CkVVdGxFbm1MRnJHekx6WVpJMjdO
            T3dSdG94ajRsRkcvV0tMUGJ2cDVWeWsKLS0tIGxxRm85Tm5mUVd4MFFxRmhQNXVE
            aEorMVhpL0t4YmlBVTVqNVJEb0FXVmcK2W3q36k9J/EoeuDnBMmr7OUWMlnhFLfA
            QkcOAFNRQHhfCEv8SwA0aBgzjpFrSHwIV2p7bbjhmDY1LnvY88ZAjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T09:32:43Z"
    mac: ENC[AES256_GCM,data:3UVXCCltMbkGv/FqCG6zJItaFxcYuwThgt2wXV/zRh5//myHkFgnhULnKv6qsGmGhW72yHjG+nzSt6RBR3n5VpajWC7tbAK5ZWnkNJxE9vYI/oAKQRGi8bcPh01grH2S5lT4hQOTaI4jqFwtKVgVWMtruDDbRQRtAt5KKOqQQvc=,iv:aVrwrT7vuRs8mkKZkq+Ao3QtJkWJ7KgVQ2WQ7BgZXDQ=,tag:W6ahvAFCkOpzUbQf/wm/QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
