apiVersion: v1
kind: Secret
metadata:
    name: maloja-secret
stringData:
    MALOJA_FORCE_PASSWORD: ENC[AES256_GCM,data:HrbjF0nH3iMjGmvaadpm0EhkxaH74X+9mR/I1YdWIg==,iv:3O5MEd5k6EtJDC+6f3u4DON2BLNfiq+2Z2gGjr/CDPg=,tag:IrXCFoCy/K+yk/e5X/5f/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SWlWcldMVWJDbGpxb1VI
            Yks3WFhpTW9vM1NIVGV6UGtieVB1eEtodTJJCng0MHhaUC93WVRhb1p1WXhFT29W
            dUt0RFhxSmpGeXhpbmNGZll2blRSRUkKLS0tIEY5dVErbkJXQ1NQeEY0TU5MTXV3
            eXMrREZuSlRCQnFncERZL2hxUzlrbEUKxY55Gp3LfF55zixIBTtw43zGLNeQpJAE
            wxwWipCC8ciPuFk3c7WWfmkAE1R/tyQnKmn0SLpunMrbudoItD/tkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-07T16:40:57Z"
    mac: ENC[AES256_GCM,data:5QPFrZ6mTHXScH113OhnVeo7WfGt42hgrNALplT1i356Pb8ubUnrAVMBfZmsxABwtWCiBJaZ5BBcikHuZ81n+7xo+AcKDkV+NDsl/j4FKZDcBvPoh/PwTZx/TeK94qWducAYnWcGqHIhAiEp70LCv1XSLBKxVFca8Fu10o68GEU=,iv:nBxlCKKTB/ASU6/NSOvZHPF79UDoNyU8p1KHKjAQ7lU=,tag:C7mHo0xSMPqdbdgpXtgreA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
