---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: qbittorrent
spec:
  groups:
    - name: qBittorrent
      rules:
        - alert: qBittorrentExporterAbsent
          annotations:
            description: |
              prometheus-qbittorrent-exporter has disappeared from Prometheus service discovery.
            summary: prometheus-qbittorrent-exporter is down.
          expr: absent(up{job=~".*qbittorrent-exporter.*"} == 1)
          for: 5m
          labels:
            severity: critical
        - alert: qBittorrentDown
          annotations:
            description: |
              qBittorrent server {{ $labels.server }} is not answering requests.
            summary: qBittorrent is Down
          expr: qbittorrent_up{job=~".*qbittorrent-exporter.*"} != 1
          for: 15m
          labels:
            severity: critical
        - alert: qBittorrentStalled
          annotations:
            description: |
              qBittorrent server {{ $labels.server }} has torrents but is not connected to any peer.
            summary: qBittorrent is stalled
          expr: (qbittorrent_torrents_count{job=~".*qbittorrent-exporter.*"} > 0) and (qbittorrent_connected{job=~".*qbittorrent-exporter.*"} != 1)
          for: 12h
          labels:
            severity: warning
