apiVersion: v1
kind: Secret
metadata:
    name: actual-sync-secret
stringData:
    ACTUAL_SERVER_PASSWORD: ENC[AES256_GCM,data:h3xVhf5JJjmMjpaJMJGgUz5KPjfy8efOGLh9VCmCnCg=,iv:4iVx5FFdwb3GacMfCb5ovEuq7pirjj2LTLQcPMKX890=,tag:KFSnI3yB0suUv4+gwE2qvw==,type:str]
    ACTUAL_SYNC_ID: ENC[AES256_GCM,data:a+OVahOF/0ToJqzzsYnC21gVpS/mXwGONreHrqpjYkpzMNl6,iv:xPf4aOuav3do260wGp5MHMxowFGf0TsvVZj93ID3MXg=,tag:1RNFBzr5VH1saBTVlRU+9g==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWW1NempCYi9uVVhxc0dP
            dnlQSjZoZkc4ZEU4b3BYV3hzOVdoQUVuZ3c0CkRlT2Jla2FBSytQZkoxTmJLckJq
            Qm0zQTBhMmR5N2ZnQWZZM0JhVHkvczQKLS0tIFV4Wm53TW5VY0hBMjFoZXVCVGI4
            d3NqMzcwTzR5Q0tjSWJ6ZmtNQjh6QkkKuimuwz5e6z02VwLLL+KTjp2zpZU2mMLz
            0VY+5zNDQ21LQi9fGFdPUlNraVg45OoxCrcVY9/TwXjsTaVmNxs8eA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-01T11:43:36Z"
    mac: ENC[AES256_GCM,data:TV8av0hPJS7RbOgMndYCvkTohd8buz3KOZY7Whl5/hqNl6tTP8dq2rBuOFd2jx2nPFWbrT15ZmnGjINs8Og3VTk3TT6A8qgo2lkoWcNsIHAF/ygrESsy9AZzP1yJXPjRMPKBJLfiy4wWPf2h09i1uQdcWiunE6jXmuz5eZM8zT8=,iv:TG20gjWFvVaQjmdC5rVGKxhEcKIsQGSBpekVt1Zr7+w=,tag:6MJE0hBgGh7b9WyE6Veagw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
