---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidarr
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled

  dependsOn:
    - name: longhorn
      namespace: storage
    - name: cnpg
      namespace: cnpg-system

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    controllers:
      lidarr:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/larivierec/lidarr
              tag: 2.10.0.4574@sha256:7c00fc609e9662c19f79365b601b113bbafced72e8f3e3f334339665e829de01

            env:
              LIDARR__APP__INSTANCENAME: Lidarr
              LIDARR__AUTHENTICATION_METHOD: External
              LIDARR__AUTHENTICATION_REQUIRED: Enabled
              LIDARR__AUTH__REQUIRED: DisabledForLocalAddresses
              LIDARR__LOG__DBENABLED: "False"
              LIDARR__LOG__LEVEL: info
              LIDARR__SERVER__PORT: &port 8686
              LIDARR__APP__THEME: dark
              LIDARR__LOG__ANALYTICSENABLED: 'false'

              LIDARR__AUTH__APIKEY: &apikey
                valueFrom:
                  secretKeyRef:
                    name: lidarr-secret
                    key: API_KEY

              LIDARRR__POSTGRES__HOST:
                secretKeyRef:
                  name: lidarr-db-app
                  key: host
              LIDARRR__POSTGRES__PORT:
                secretKeyRef:
                  name: lidarr-db-app
                  key: port
              LIDARRR__POSTGRES__USER:
                secretKeyRef:
                  name: lidarr-db-app
                  key: user
              LIDARRR__POSTGRES__PASSWORD:
                secretKeyRef:
                  name: lidarr-db-app
                  key: password
              LIDARRR__POSTGRES__MAINDB:
                secretKeyRef:
                  name: lidarr-db-app
                  key: dbname

              TZ: ${TIMEZONE}

            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

            resources:
              requests:
                cpu: 10m
                memory: 256Mi

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: [ 'ALL' ] }

          metrics:
            dependsOn: app
            image:
              repository: ghcr.io/onedr0p/exportarr
              tag: v2.0.1

            args: [ 'lidarr' ]

            env:
              PORT: &metricsPort 9707
              URL: 'http://{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.app.ports.http.port }}'
              APIKEY: *apikey
              ENABLE_ADDITIONAL_METRICS: true
              LOG_LEVEL: warn

            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 125Mi

    service:
      app:
        primary: true
        controller: lidarr
        ports:
          http:
            port: *port
      metrics:
        nameOverride: metrics
        controller: lidarr
        ports:
          metrics:
            port: *metricsPort

    serviceMonitor:
      metrics:
        enabled: true
        serviceName: lidarr-metrics
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 10m
            scrapeTimeout: 2m

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: sh-lidarr.svg
          gethomepage.dev/name: Lidarr
        className: internal
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        existingClaim: lidarr-2

      tmp:
        type: emptyDir

      media:
        type: nfs
        server: ${SECRET_NAS_IP}
        path: /volume1/Media
        globalMounts:
          - path: /Media
