---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
  dependsOn:
    - name: longhorn
      namespace: storage
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: "0.49.0@sha256:56eb0be42972c016c9b0902b3b25d94e24a7606ab70368764e540fc7128b0c6d"
            env:
              TZ: ${TIMEZONE}
              PORT: &port 5000
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123
          browser:
            image:
              repository: docker.io/browserless/chrome
              tag: latest@sha256:57d19e414d9fe4ae9d2ab12ba768c97f38d51246c5b31af55a009205c136012f
            env:
              SCREEN_WIDTH: "1920"
              SCREEN_HEIGHT: "1024"
              SCREEN_DEPTH: "16"
              ENABLE_DEBUGGER: "false"
              PREBOOT_CHROME: "true"
              CONNECTION_TIMEOUT: "300000"
              MAX_CONCURRENT_SESSIONS: "10"
              CHROME_REFRESH_TIME: "600000"
              DEFAULT_BLOCK_ADS: "true"
              DEFAULT_STEALTH: "true"
    service:
      main:
        controller: main
        ports:
          http:
            port: *port
    ingress:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Tools
          gethomepage.dev/icon: changedetection-io.png
          gethomepage.dev/name: Change Detection
          gethomepage.dev/widget.type: changedetectionio
          gethomepage.dev/widget.url: http://changedetection.default.svc:5000
          gethomepage.dev/widget.key: ${SECRET_HOMEPAGE_VAR_CHANGEDETECTION_API_TOKEN}
        className: internal
        hosts:
          - host: change-detection.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    persistence:
      config:
        existingClaim: changedetection
        advancedMounts:
          main:
            main:
              - path: /datastore
