---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./grafana/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./loki/ks.yaml
  - ./smartctl-exporter/ks.yaml
  - ./unpoller/ks.yaml
  - ./promtail/ks.yaml
  - ./tailing-sidecar-operator/ks.yaml
  - ./apprise/ks.yaml
