---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: akri
spec:
  interval: 30m
  chart:
    spec:
      chart: akri
      version: 0.13.8
      sourceRef:
        kind: HelmRepository
        name: akri-helm-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    prometheus:
      enabled: true

    udev:
      discovery:
        enabled: true
        resources:
          cpuLimit: 48m

    agent:
      resources:
        cpuLimit: 52m
