apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-zigbee-dongle
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      groupRecursive: true # Recommended unless using very exact udev rules
      udevRules:
      - ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60"
    name: udev
