apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-zigbee-dongle
spec:
  capacity: 1

  discoveryHandler:
    name: udev
    discoveryDetails: |+
      groupRecursive: true # Recommended unless using very exact udev rules
      udevRules:
      - ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60"

  brokerSpec:
    brokerPodSpec:
      containers:
        - name: zigbee-dongle-broker
          image: alpine:3.14.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |-
              set -euxo pipefail
              echo Installing ser2net
              apk add --no-cache ser2net
              UDEV_DEVNODE="$(env | grep '^UDEV_DEVNODE' | head -n 1 | cut -f2 -d=)"
              echo $UDEV_DEVNODE
              ser2net -d -C 2000:raw:0:$UDEV_DEVNODE:115200
          ports:
            - name: device
              containerPort: 2000
          resources:
            requests:
              "{{PLACEHOLDER}}": '1'
              cpu: 10m
              memory: 50Mi
            limits:
              "{{PLACEHOLDER}}": '1'
              cpu: 100m
              memory: 200Mi

  configurationServiceSpec:
    type: ClusterIP
    ports:
      - name: device
        port: 2000
        protocol: TCP
        targetPort: device
