---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: Europe/Stockholm
  LOCALE: sv_SE.UTF8
  NODE_CIDR: "192.168.0.0/24"
  POD_CIDR: "10.69.0.0/16"
  SERVICE_CIDR: "10.96.0.0/16"
