apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mLi6uceKJ/UZ7A==,iv:pasaX77vmNfSGf8IOHrrGEh412lTccBqGDF5AH+BE0E=,tag:Bv9QJBrSlP4LPpAKFQf5EA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:IYv7HU4G3ckiyDriMr0xZqfvJxLqNJyDsw==,iv:/jzrECBE3ccUoiCs4I4EF/4me2TfCf31aHSeVnJ0KJs=,tag:IKvnVL2sJ7fW6ZSaxZ39Wg==,type:str]
    SECRET_MY_EMAIL: ENC[AES256_GCM,data:xb8kQVr3YggVmWb1ZV0SWVBR54+VnX9zJw==,iv:AScCEhDiocCOQkk0PLSe4pmBUnlqz7a4Yd4WvvGZ7Zs=,tag:QEighA8tovJoQhc5qEehEQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:quMHAsyB6QloKdtjwpYwYuE6QkI9Rl8e1YF6ISseaVYaxpXs,iv:ojbAomz6nK52VGEPPnn4l1FJ4nIlOGCgHeD29RhsXME=,tag:Eok4tI6mCdeTev0U9ehpOQ==,type:str]
    SECRET_NAS_IP: ENC[AES256_GCM,data:iQSNB8kDaOLpVybLTw==,iv:9x0LQWhwmfCznesMTO8CQsEjrtUGtMp0/OEWWr4cd0w=,tag:l7Ae53tLgzZIrRufHcJUag==,type:str]
    SECRET_HOMEPAGE_VAR_CHANGEDETECTION_API_TOKEN: ENC[AES256_GCM,data:GM1GvpKp,iv:iCY9nIXarcO9hiWBzVto/4LWn0eqGoxQ56i47bxnflA=,tag:Axj/ycSUP91WP01say1RvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcHVVL25BQkY0VFhVRnBF
            SEEydU9GcU9BR1Q2SndJS1d4S1FlV1M5MlF3CklZWHhnYWtHZDhVb1l0Y0k2U1hr
            YnZvdXgrQ0RzcmVIWmxQcmkwc3NHcE0KLS0tICtJaXo1UWdwM1VNdFdZeHRDdzlE
            UlprR0tCRDRVcVk1bnhOdHlKNDdhdmsKNcLo/FL3H/vKk9otvWC2Txgmln/3yrfE
            ISPOF2+6X9ScYiGQWMheADy7aqqdZ00MwG0NLSWmYBOg0ZmU8ttZZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-12T14:11:48Z"
    mac: ENC[AES256_GCM,data:ev4eHXYoPM33pw9UBel+ZTs0e3lXb6ntfiVoMtgG7eQqPR5q15H9HcrHZ7ZdHfUcscTKe6lREb23lhfhL0DmDiUQwtUBFectKRjhov6TkeHm8C+p3I5MbiMJoakvzXhgY8lz86r0BI3QqkaWkgBiKljbjQvuAGP/r1VODLQ+Znk=,iv:Jghkhb00WcRrlVWGy7W1IihKSrlFy2RMwbgANnfkobI=,tag:2fXB9p/QcFSrOku7huGNZw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
