apiVersion: v1
kind: Secret
metadata:
    name: feed-monitor-registry
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:nE2+yBPyph9WTZFAgf0VRmwtAZUR2tY8Xwyp/UAVF8atumO8zW7CQIfleV09cvMtl/4uOBFMndl+h7x1fxWlfWIInl8CoP9+DvpJ+xR/QxrFTlx/6cVyv+lSc87qG8SKCGsHSuWr5/Q=,iv:i9T31IMp9QkGZXo58NH3spwf5X/eYXpHJGfjNHPkzN4=,tag:JF+N2YDVDGAB1cJHeQx+/g==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNy82SFRaa2xnNkdsRnNR
            WFpBSm53R05ScWlPTnlWZ3RSRGd2c04vaVNrCkN1Nk44b2hmeHlCVTdUYmphQTFj
            TzNSZDNWQ1Zhemlic2dPczVmUlhaVVEKLS0tIFZVdGtSOTFZVnZ5QmtsM2VRcUNj
            VThIaldKc2w1NG13dVdLTzZhTDU0ejAK1P5vyZoC+gm8mBVwmq0MY3Hi7wpLST8S
            4ZGHGPcGwIuWDcIgNrRIVHBvn7fQqQjUcjJRhh5pdIFRVZEVbaXNNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-03T14:35:27Z"
    mac: ENC[AES256_GCM,data:YzqKwu4oF2rn9LDkFfx9s9V/4tZCRRtDu0Akwuro+0aXQgCkRzhmn2jOk83kQ8uoSR1n0LCViB7Miwzywz7KiF0nLzfJeQZ9k0CNKSPeYsTWfxHtDuAqEpZZbe3RXp0X+37Sj3f141UBqdLUIdCRx3QIRL18ZEY3WLMaQ0WC6uo=,iv:0t1wj3ruhbo74Kwx7n9pd3cmdOQbhcDxcRBqp81Iew8=,tag:z95ChlAsnqEoJoyQiSFSmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
