---
devices:
  - # Sonoff Zigbee 3.0 USB Dongle Plus V2
    name: zigbee-dongle
    groups:
      - paths:
          - path: /dev/serial/by-id/usb-Itead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_V2_585cda3eca8bee11971703028acbdcd8-if00-port0
