---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: emqx
      namespace: database
  driftDetection:
    mode: enabled

  values:
    controllers:
      zigbee2mqtt-exporter:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 2000
            runAsGroup: 2000
            fsGroup: 2000
            fsGroupChangePolicy: OnRootMismatch

        containers:
          zigbee2mqtt-exporter:
            image:
              repository: ghcr.io/kpetremann/mqtt-exporter
              tag: 1.7.1
            env:
              LOG_LEVEL: INFO
              MQTT_IGNORED_TOPICS:
              MQTT_ADDRESS: emqx-listeners.database.svc.cluster.local
              MQTT_PORT: 1883
              MQTT_TOPIC: "zigbee2mqtt/#"
              MQTT_KEEPALIVE: 60
              MQTT_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: ZIGBEE2MQTT_CONFIG_MQTT_USER
              MQTT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: zigbee2mqtt-secret
                    key: ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD
              PROMETHEUS_PORT: 9000
              PROMETHEUS_PREFIX: mqtt_
              TOPIC_LABEL: topic
              ZIGBEE2MQTT_AVAILABILITY: "True"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 5m
                memory: 64Mi
              limits:
                memory: 256Mi

    service:
      app:
        controller: zigbee2mqtt-exporter
        ports:
          metrics:
            port: 9000

    serviceMonitor:
      app:
        serviceName: zigbee2mqtt-exporter
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 30s
            metricRelabelings:
              - sourceLabels:
                  - topic
                targetLabel: topic
                regex: "zigbee2mqtt_(.*)"
                replacement: "$1"
