---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: zigbee2mqtt-exporter
spec:
  groups:
    - name: zigbee2mqtt-exporter
      rules:
        - alert: MqttExporterAbsent
          expr: absent(up{job="zigbee2mqtt-exporter"} == 1)
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: The zigbee2mqtt-exporter exporter job is absent
            description: The zigbee2mqtt-exporter exporter job is absent
        - alert: Zigbee2MqttUnavailable
          expr: absent(mqtt_zigbee_availability == 1)
          for: 30m
          labels:
            severity: critical
          annotations:
            summary: The zigbee device connection is lost
            description: connection on topic {{$labels.topic}} is down
        - alert: Zigbee2MqttLinkqualityLow
          expr: mqtt_linkquality < 15
          for: 60m
          labels:
            severity: warning
          annotations:
            summary: The zigbee device link quality is low
            description: link quality on topic {{$labels.topic}} is at {{$value}}
        - alert: Zigbee2MqttBatteryLow
          expr: mqtt_battery < 40
          for: 60m
          labels:
            severity: warning
          annotations:
            summary: Low battery - {{$labels.topic}} ({{$value}}%)
            description: battery level of {{$labels.topic}} is at {{$value}}%
        - alert: Zigbee2MqttTemperatureHigh
          expr: mqtt_temperature > 50
          labels:
            severity: warning
          annotations:
            summary: Temperature high (>50c)
            description: temperature on topic {{$labels.topic}} is {{$value}}c
        - alert: Zigbee2MqttFreezerTemperatureHigh
          expr: mqtt_temperature{topic="frystermometer"} > -10
          labels:
            severity: critical
          annotations:
            summary: Freezer temperature high (>-10c)
            description: temperature on topic {{$labels.topic}} is {{$value}}c
        - alert: Zigbee2MqttFridgeTemperatureHigh
          expr: mqtt_temperature{topic="kyltermometer"} > 8
          labels:
            severity: warning
          annotations:
            summary: Fridge temperature high (>8c)
            description: temperature on topic {{$labels.topic}} is {{$value}}c
        - alert: Zigbee2MqttSmokeDetectorAlert
          expr: mqtt_smoke > 0
          labels:
            severity: critical
          annotations:
            summary: A smoke detector is in state alarm
            description: smoke detector on topic {{$labels.topic}} is reporting smoke
        - alert: Zigbee2MqttWaterLeakAlert
          expr: mqtt_water_leak > 0
          labels:
            severity: critical
          annotations:
            summary: A water leak detector is in state alarm
            description: water leal detector on topic {{$labels.topic}} is reporting water
