apiVersion: v1
kind: Secret
metadata:
    name: qui-secret
stringData:
    QUI__SESSION_SECRET: ENC[AES256_GCM,data:d+CyRlxh6cdQZrMcaUs02YofcNsevifbYXnd9/G2H+Zn35jQCE1ZkF1pGzgfGwbg6FwsL4nCuLtsZdDEj9xs5g==,iv:toAXDXn2aeYnF6Md4w8gpPpu5Mel/bdBzdz/khNqVxU=,tag:7phkHD17gCoz5U8+x7vDiw==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTUhEQU9NdTN4K0dMVFFq
            VVEwUk56NHBDTkVyUS9tclM4L1ZHTjg2VjJZCnBzNTlZaTIrUTNrRVhnK0hhUzFO
            S1JaTWNrWDJlNmpPNW50NU9oSnZVRXMKLS0tIDVvU0t1eDd2c2gyay9YUkVWc0kv
            Z2E2V2xtTllHbjdWNWxJaGZWbFBkc3MKaaH1xefCe7FH1yJNLfkEMn9q5BtEuh1M
            rsI/NBZEvEMOUgN/zLnIKqr7m1Tpr8tYx2ttaQZjcUMapBMUdmFLJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T14:44:14Z"
    mac: ENC[AES256_GCM,data:HyN42jPaZ+hWzNJlJbtCEZyqYc5SSkC7al4CsYrqBtBa6yNWEWF3JpgdzQ+g6mwLKzR9NMgcTxMdhZnsF6ufZCh8lzoGUQ7d66hACD43Ps37vh+qvtsm1IOffkocUG87zBUYr4ubTrNIqBW5BBK4SkPwmv5E0Tc5x6/3PjAM4iU=,iv:GeUemEJOVSkYSMxdJaPYHBVwgCcFNtz/dQ5NfqWLrm4=,tag:a/459Umt9aXNrYIPStZgyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
