---
apiVersion: v1
kind: Service
metadata:
  name: nas-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nas.${SECRET_DOMAIN}
    external-dns.alpha.kubernetes.io/target: ${SECRET_NAS_IP}
spec:
  clusterIP: None
