apiVersion: v1
kind: Pod
metadata:
  name: pvc-temp
  namespace: default
spec:
  volumes:
    - name: dev
      hostPath:
        path: /dev
    - name: sys
      hostPath:
        path: /sys
    - name: var-lib-kubelet-device-plugins
      hostPath:
        path: /var/lib/kubelet/device-plugins
  containers:
    - name: noop
      image: debian:bullseye
      command:
        - /bin/sh
        - -c
        - |
          while [ true ]; do
            sleep 5
          done
      volumeMounts:
        - name: dev
          mountPath: /dev
        - name: sys
          mountPath: /sys
        - name: var-lib-kubelet-device-plugins
          mountPath: /var/lib/kubelet/device-plugins
