apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:aND2x6IfOnxdw7rvVHWYuGKdZsatribdr/mBr0qzC/M=,iv:cM9P8E44jij1YfI1V6kU0qc2rPpDDHf4Q/jIG8i7un0=,tag:lqkmq/TUo7V4LeE147Xhhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ckp4ZzlocC9qZnpYakk4
            SDdkZCtTRG9mVFdXamdzUGtNVEVVQTlCYXlZCjZvOUYzam1aRzNoNFNudC9rNDcx
            Vk1aUXBTVDhSM25vVVFBcDBSaG5ybWcKLS0tIE1Hc09yazAzUHRTN2ZhMHU2SDUv
            YWNCcTFBZWVCSVkyTnU5RjhtV3I0Q2sK3x5IIhRU/QK+4ZFKmsRnqDtwi+oKj4xX
            c8BphvpS+P8KcG/xp5W6YD7daXRB+s9tAqwZ1HW4wfAK+z3Hko2KKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T16:25:58Z"
    mac: ENC[AES256_GCM,data:CI8+hm0Gxb2xh1jTsPfzfVZZCo9Z5FaWSlg6gU019Eaf3A9hjxtSYdudAAeugPHFE5Ap8GfpxXvegCoQflbysQA6G0F0z7A1cf5xNmAABzpAZbCDdGJtlGr48aIJUPjSEVtoAWULshKkyyePyCuWFxm3SStnFXDK+J1QoZRyPQ4=,iv:MrOkMHXqSM3dInQVLtB/Hn1yr619wpL6s4C8khhgC5Q=,tag:91aTB1zSjz8edLdj+zlFSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
