---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
  dependsOn:
    - name: longhorn
      namespace: storage
    - name: cnpg
      namespace: cnpg-system
  values:
    controllers:
      mealie:
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v2.4.1@sha256:efd4001597fbcea58aa1e2ff54f5e5b5f8fe6237df6862a2e4576dcb5ff0d24e
            env:
              TZ: ${TIMEZONE}
              ALLOW_SIGNUP: "false"
              BASE_URL: https://recipes.${SECRET_DOMAIN}
              DB_ENGINE: postgres
              POSTGRES_USER:
                secretKeyRef:
                  name: mealie-db-app
                  key: user
              POSTGRES_PASSWORD:
                secretKeyRef:
                  name: mealie-db-app
                  key: password
              POSTGRES_SERVER:
                secretKeyRef:
                  name: mealie-db-app
                  key: host
              POSTGRES_PORT:
                secretKeyRef:
                  name: mealie-db-app
                  key: port
              POSTGRES_DB:
                secretKeyRef:
                  name: mealie-db-app
                  key: dbname
            envFrom:
              - secretRef:
                  name: mealie-secret
            resources:
              requests:
                cpu: 100m
                memory: 128M
              limits:
                memory: 512M
    service:
      app:
        controller: mealie
        ports:
          http:
            port: 9000
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        className: external
        hosts:
          - host: "recipes.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: mealie
        globalMounts:
          - path: /app/data
