---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v3.3.1@sha256:a0d4a0b8543389ff3259eae40ffedeea94364f9229aa945a3e9d69e7a03e30ad
            env:
              TZ: ${TIMEZONE}
              ALLOW_SIGNUP: "false"
              BASE_URL: https://recipes.${SECRET_DOMAIN}
              DB_ENGINE: postgres
              POSTGRES_USER:
                secretKeyRef:
                  name: mealie-db-app
                  key: user
              POSTGRES_PASSWORD:
                secretKeyRef:
                  name: mealie-db-app
                  key: password
              POSTGRES_SERVER:
                secretKeyRef:
                  name: mealie-db-app
                  key: host
              POSTGRES_PORT:
                secretKeyRef:
                  name: mealie-db-app
                  key: port
              POSTGRES_DB:
                secretKeyRef:
                  name: mealie-db-app
                  key: dbname
            envFrom:
              - secretRef:
                  name: mealie-secret
            resources:
              requests:
                cpu: 100m
                memory: 128M
              limits:
                memory: 512M
    service:
      app:
        controller: mealie
        ports:
          http:
            port: 9000
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Services
          gethomepage.dev/icon: sh-mealie.svg
          gethomepage.dev/name: Mealie
          gethomepage.dev/widget.type: mealie
          gethomepage.dev/widget.url: "http://mealie.default.svc:9000"
          gethomepage.dev/widget.key: ${SECRET_HOMEPAGE_VAR_MEALIE_API_TOKEN}
          gethomepage.dev/widget.version: "2"
          gethomepage.dev/widget.fields: '["recipes", "users", "categories", "tags"]'
        className: external
        hosts:
          - host: "recipes.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: mealie
        globalMounts:
          - path: /app/data
