apiVersion: v1
kind: Secret
metadata:
    name: mealie-secret
stringData:
    SMTP_HOST: ENC[AES256_GCM,data:XUTEMPnnJG5Sl66ugyPKCQ==,iv:2yIIMK+1gjAokiiNjhFwU59f/zwdGixXC7umTtHUXeo=,tag:Kuh767Ez1kbzSgpkKOD15g==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:ozcy,iv:MpMQdtPEH2J4yzY7zS+hNr2CoC0oMx8vFB9y2uGCV6w=,tag:UZNFC7WmQLh52J4JCeWBQA==,type:int]
    SMTP_FROM_NAME: ENC[AES256_GCM,data:Sycy0Q8s,iv:3unR3rZC6oor3fierl+ojFeyhlsDeFaQh5GGOsje88E=,tag:NovDpoLcM1K8KQM5pZltRw==,type:str]
    SMTP_AUTH_STRATEGY: ENC[AES256_GCM,data:HOy9,iv:Ug6A//sEFBdadimLWV2Dl4BKNF5jQFN6raCN+fF3ZHk=,tag:nDlTMxSsyCa84wFi8Ti6ng==,type:str]
    SMTP_FROM_EMAIL: ENC[AES256_GCM,data:nzKPvDgNSxTMi5zCp32rOWc=,iv:qQIMzJg91uoSfnmA8Ar91aSDoVMRvSB/jOrcfjFz4J4=,tag:tUnQHj5rd7HVgR6yfU4D3w==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:dt3hUV485jvIMV4h8YpjrNGKG/Ii3tzHs27GroKHWTo=,iv:YNCsh+/rDQkzgK3XPpfbGfth1X7gWkHbM2VJGbfOlro=,tag:xlIvRm5jqWD21FkQlNs2kQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:ZD5h9OnZUa8baTRKQ9S9eODbE5xE9wpdZABcBlQL+1A=,iv:uoumyLqqULZHEshJpDeLmVAiswKJTHaDmksQ+pHG5tM=,tag:n772zWV/Vn7kYVErewGu6A==,type:str]
    OPENAI_BASE_URL: ENC[AES256_GCM,data:o9g8Ia71ihpT+LUb/U1xzL1m7sabOyS4Qg==,iv:xDeYC7KZgKjcHXIafyjs80XvGK4z1Pd41rlTKE/otNE=,tag:G/OFRtnXNxHFYjid+FXWgg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:NyDHcav4ftq4LZ3k8r/Afb0hLe86M627qOASryByvumfr1WAbiAkON1hBc8l6dLFS2qPhBVeZR3vnYQ1rm6L4WxxMhmZoWkaT5VEl6L7+M4JSajYihgcacMvGB/XoOVWO4hhTmF3xjDWAC7iukw6r9Quo8Po1TZL9mRch1NOPFIzayvTNv53bunlaZChnDEQrqttt+sKL7rNQ0Ew0i2Giz5ECbE=,iv:xFb/JpNMlHZPdpjLGUnMSEaAtDpb4FC61dSUZ2OhuUk=,tag:kriyOzcO9MDD2EwKWnW6EQ==,type:str]
    OPENAI_MODEL: ENC[AES256_GCM,data:/coOhlrEQZQjsK4=,iv:B3DYJ9fM7EFqpyguYSFv0hFJdYnoq8g8nyP247V/j80=,tag:aPjZ7MwDi6QoHJVfqd+u/w==,type:str]
    OPENAI_WORKERS: ENC[AES256_GCM,data:qQ==,iv:oKinkXvzrQHormJVsP/miJm4G0cOesz3k9DB1hlpsC4=,tag:rB+J2HarSw/P7nK02ZRwQQ==,type:int]
    OPENAI_SEND_DATABASE_DATA: ENC[AES256_GCM,data:c7lh2cU=,iv:v+g3A8LBJyL4seEtgNKK9ZXg79qEXbqw/trSm28YLAU=,tag:l7oorv1mRuolv7e0hsAJoA==,type:bool]
    OPENAI_REQUEST_TIMEOUT: ENC[AES256_GCM,data:pP8=,iv:G9cP14I6kATJVf3pgJktXLsAcy3mLKc4SvmS/6xpZL8=,tag:c3MqbsbejqxikRiug5VQ7A==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOHBGTFlhdkpGUDZkNnNC
            S0ZGNUxrR0ZwYWJUa2lDKzY2ZVZDVXRESmdZCnJ2NXFYQkFNTDhGYmF4TjBMUDZ0
            b1UvdDkrbi9hcXJ2U2xVL2laSmNFS1kKLS0tIG80SXJkQ0haZEwvLzl1eDluSEJy
            aWFIckdUVkQ2WGwxbE8vZlc4RlFQTVUKzSiq5AuMmTJXK42cVvDDAoI/Zx5tSwM5
            egTv/UqCUMPO5bt/arOo8xGZJ12wXkPq3EiLtujOCJt1H9oNR/Jw7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-06T12:11:10Z"
    mac: ENC[AES256_GCM,data:gQzG95r+Gdz7X378mkX9pNUttuu2sz6C1KaR0DzeU1z1aYe0+qC1SOo+NZV5c96E5fpqmBKF+r/VtfoO3ron3gBBbY1z6Q6JfAaRW4DK1yVSARFz1Q1UemrXD2ptQJBL9icBzf0ZXgHWGpBlylq+CU6L30qw0RyemRk42qIZZPc=,iv:cXFirSFaOSKH3tVMuLhzknt1prOQtLE33x6kRNg+T1I=,tag:k+aipLXgn8FVJLRBY1dcVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
