---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: jameswynn-charts
        namespace: flux-system
      interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 4
  driftDetection:
    mode: enabled
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.10.9

    # Enable RBAC. RBAC is necessary to use Kubernetes integration
    enableRbac: true

    extraClusterRoles:
      # - apiGroups:
      #   - some-group
      #   resources:
      #   - some-resource
      #   verbs:
      #   - get

    serviceAccount:
      # Specify a different service account name. When blank it will default to the release
      # name if *create* is enabled, otherwise it will refer to the default service account.
      name: ""
      # Create service account. Needed when RBAC is enabled.
      create: true

    service:
      main:
        ports:
          http:
            port: 3000

    controller:
      annotations:
        reloader.stakater.com/auto: "true"
      strategy: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%

    # Enable the ingress to expose Homepage to the network.
    ingress:
      main:
        enabled: true
        # labels:
        #   # This label will enable discover of this deployment in Homepage
        #   gethomepage.dev/enabled: "true"
        # annotations:
        #   # These annotations will configure how this deployment is shown in Homepage
        #   gethomepage.dev/name: "Homepage"
        #   gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
        #   gethomepage.dev/group: "A New Group"
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${SECRET_DOMAIN}
        className: internal
        hosts:
          - host: "start.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix

    # All the config files for Homepage can be specified under their relevant config block.
    config:
      bookmarks:
        - Developer:
            - Github:
                - abbr: GH
                  href: https://github.com/martinjonsson01/
            - Renovate Dashboard:
                - abbr: 🤖
                  href: https://github.com/martinjonsson01/cluster/issues/2
        - Social Media:
            - Reddit:
                - abbr: R
                  href: https://old.reddit.com/
            - Twitter:
                - abbr: TW
                  href: https://x.com/home
            - Hacker News:
                - abbr: HN
                  href: https://news.ycombinator.com/
        - Entertainment:
            - Youtube:
                - abbr: YT
                  href: https://www.youtube.com/

      services:
        - Home Automation:
            - Home Assistant:
                widget:
                  custom:
                    - state: sensor.athom_cluster_plug_power
                    - template: "{{ states.switch|selectattr('state','equalto','on')|list|length }}"
                      label: switches on
                    - state: weather.forecast_hem
                      label: wind speed
                      value: "{attributes.wind_speed} {attributes.wind_speed_unit}"

      widgets:
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "cluster"
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
        - longhorn:
            expanded: true
            total: true
            labels: true
            nodes: true
      kubernetes:
        # change mode to 'cluster' to use RBAC service account
        mode: cluster
      docker:
      settings:
        title: Services
        headerStyle: boxedWidgets
        cardBlur: sm
        hideVersion: true
        disableCollapse: false

        layout:
          - Home Automation:
          - Selfhosted:
          - Media:
          - Household:
          - Observability:
          - Tools:
          - Downloads:
          - Social:

        providers:
          longhorn:
            url: http://longhorn-frontend.storage.svc:80

    # -- Main environment variables. Template enabled.
    # Syntax options:
    # A) TZ: UTC
    # B) PASSWD: '{{ .Release.Name }}'
    # C) PASSWD:
    #      configMapKeyRef:
    #        name: config-map-name
    #        key: key-name
    # D) PASSWD:
    #      valueFrom:
    #        secretKeyRef:
    #          name: secret-name
    #          key: key-name
    #      ...
    # E) - name: TZ
    #      value: UTC
    # F) - name: TZ
    #      value: '{{ .Release.Name }}'
    env:
      TZ: ${TIMEZONE}

    persistence:
      logs:
        enabled: true
        type: emptyDir
        mountPath: /app/config/logs

    resources:
      requests:
        memory: 10Mi
        cpu: 10m
      limits:
        memory: 200Mi
        cpu: 500m
