---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
spec:
  instances: 2
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.5-0.3.0
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  storage:
    storageClass: openebs-hostpath
    size: 8Gi
  resources:
    requests:
      memory: 20Mi
      cpu: 10m
  monitoring:
    enablePodMonitor: true
  smartShutdownTimeout: 1
  stopDelay: 301
