apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:5skH7g==,iv:5tsGvlzknp5wfm7rNju7+u+f73Ds90SI7nr+YHJHZAE=,tag:AViGwiLckvrLTjJmTGmLyQ==,type:str]
    PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:FfYdupsQ+1SNyqXv9QqDFM/9j2V+gFM=,iv:UiAgcbVidhgfy4Fn5jN43AEaHgrHoMfXGrBLE2eT9aE=,tag:/4yiOvuPGWbNbqmMywPO6g==,type:str]
    PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:IreYkUlr3MbnIOWcQggUkWl32zqvnYlQ,iv:nfSYXtXvJgbZZeUiQ91DykBlpYpRdm4RXjNlG7HCZWo=,tag:PPSpDoWRION6ANH7ITjMzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YWpMOVY3aEtLMEFmai9M
            dC9PMS9XZGo1cTNnWWxZOE55Q21PSTZGc2p3Ck9FWm9Bc0V1NThqUUU0ODUzRDls
            UG1CbjN2ZC80VUYwQjNERW9IVXExUG8KLS0tIGF1K0w0ZXVLNWFaUGNCQ01YWEpy
            L1F5aU44cG1zRTVwSHB6dWZGUmhRS28KDlW22tC4eSrFJhAImxATi3K/nyVMNiFX
            EM7Y4F9McB+AOI9JrK3afdKUoLE3C5LIdjuw1+iQy7yAxh5ToBrn8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T12:45:25Z"
    mac: ENC[AES256_GCM,data:nS9FXqz7ZU9yWvIto/Ww5uetugbNnY5u+YNcP8GJh79NKA70y6jsZJUVp85peBm7/JZoIsDjrxUah4t2Il1etQsMHMullQTV6hrSdi99HpWIzyMz/Q6f16LCtuqJpkP0U+a0aI16525g2CZFqY/gwP91mCwH+Gt6E6RGXZV4lt4=,iv:yUcQB3fokbeRsyldqCm/LRbqZwe5kqEyU0/idTYSo3o=,tag:MIFtZxgJNKtwbBmJngBi/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
