apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:4S9YU7g52qCSDulViV6pqJOy/0g4uS1EP11Nd3xZZ/88/wc1M4/RxLbpH6KZJkbvRuH9GKkTTb897Fz3KFkVo6LviIKLOoHzobMsPYxs1uNMsJI4u4q13tIMMYq5RuH0f/UcbuOk8szfqcCE+M/8uTBeRFEPGw==,iv:4TjNYeK6dgMGS72T1ZicgNCJDeyUGhXqGmw2BZfkLgo=,tag:pc8RFsYOZ1vSAIZQxqg5hg==,type:str]
    PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:4NTYKAqfhBFjVykFQb8lLdw/XCc9FIsVLFsHX+XU8HyVubod,iv:UFH2IrgfTy4gIFtOS/BehbzwgdiMtTf/y5jDfccypIg=,tag:ZeDwTug+IZTJC1aRDlL/gA==,type:str]
    PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:Th5SoS+iDlvbW2I1EWcflb1A/wE=,iv:t19n9rJGMqOkIbsSuo0KvokF1bAuo1AoaGIZToowIwA=,tag:XwYDLUnKTXnXmGieJSsZag==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:1mINMKwvQ7tlFKkvI0jDBA==,iv:u3jzyblwMpi/ReiiYaRhiWRhzSqtDW/JhrtETbmk8yE=,tag:7mlnjuK/OzSnqs4M+4qYgA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:Ttzj297u6F4eniXF2itKhY63nK4Ylg==,iv:Rj/jOEqTDoP1owCKg3a1KgNJ04cCOT0HILZlxYFC/bs=,tag:cj61uOTHSfb8gtxJojqJ4g==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:nnO7,iv:MB2Sm/bsiQMc/bFjOkiZROPvJNHkzA0UqZFXXaLx3BY=,tag:CmxhP17xMFz/qg201rPawg==,type:int]
    SMTP_SECURITY: ENC[AES256_GCM,data:w3MMS5L9cXQ=,iv:z55Jmj4LZLToSik7jzNrdy4+8uGPKQhteC7jkURsrxM=,tag:yCD0Za0EM58l8OonUnIf5Q==,type:str]
    SSMTP_STARTTLS: ENC[AES256_GCM,data:jro/,iv:x22e6qVnpFq0dTyJHh0wsvo+Z5bhddBudu/yfovh+c8=,tag:e51sHzcCl8oLimDzW5ASXA==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:NYRHN9B183osWuE5jnMRjgNalyFgPc2HcNTftBHj7eY=,iv:B3vAXRzE+XOhbjQWMscqNZH1hx+FDeGHOVwCsdn0zZM=,tag:9/wdYfiWNzv/8NKRWMClvA==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:9wVJUZeQ4xBdAKaArDK0qx/nGoXUGOMgRBSPTeYGqSc=,iv:/8pjWEObDTey1Rwl2DvkFzyeimNuvS8LQKLzROEP2QQ=,tag:G3S7fg/HQZKg2N1s0BT23g==,type:str]
    dummy: ENC[AES256_GCM,data:59KY+kuZyA==,iv:+AMsdxedT9GFpR3PXqF0CYJk9Kiuwt5y9hJCNFjqqSs=,tag:blV2Vuz36NZMjPAyZfUV1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YWpMOVY3aEtLMEFmai9M
            dC9PMS9XZGo1cTNnWWxZOE55Q21PSTZGc2p3Ck9FWm9Bc0V1NThqUUU0ODUzRDls
            UG1CbjN2ZC80VUYwQjNERW9IVXExUG8KLS0tIGF1K0w0ZXVLNWFaUGNCQ01YWEpy
            L1F5aU44cG1zRTVwSHB6dWZGUmhRS28KDlW22tC4eSrFJhAImxATi3K/nyVMNiFX
            EM7Y4F9McB+AOI9JrK3afdKUoLE3C5LIdjuw1+iQy7yAxh5ToBrn8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T13:50:17Z"
    mac: ENC[AES256_GCM,data:ZNn3hA7OIoahDHWcOZ3/eOe0Qq5AkDDOEi52z2h/HhWSNbv4XHluS/zMRGYlfhLkg+3US7WgUGpk86DR5bdl9XVzi9rI1qqkdT4thqgqjjotzubQlSGFb+KD0HLk4GQCybuOIkV/MnvNxuw7GEx3Z8BqpEGvgnZNRV07m/sZXXs=,iv:BNFInHfinjGVLWYFxJlaFb6F5XT4DY56rZQLWurr+kk=,tag:R4ctSnztugJgGoGVprGfcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
