apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:4S9YU7g52qCSDulViV6pqJOy/0g4uS1EP11Nd3xZZ/88/wc1M4/RxLbpH6KZJkbvRuH9GKkTTb897Fz3KFkVo6LviIKLOoHzobMsPYxs1uNMsJI4u4q13tIMMYq5RuH0f/UcbuOk8szfqcCE+M/8uTBeRFEPGw==,iv:4TjNYeK6dgMGS72T1ZicgNCJDeyUGhXqGmw2BZfkLgo=,tag:pc8RFsYOZ1vSAIZQxqg5hg==,type:str]
    PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:4NTYKAqfhBFjVykFQb8lLdw/XCc9FIsVLFsHX+XU8HyVubod,iv:UFH2IrgfTy4gIFtOS/BehbzwgdiMtTf/y5jDfccypIg=,tag:ZeDwTug+IZTJC1aRDlL/gA==,type:str]
    PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:Th5SoS+iDlvbW2I1EWcflb1A/wE=,iv:t19n9rJGMqOkIbsSuo0KvokF1bAuo1AoaGIZToowIwA=,tag:XwYDLUnKTXnXmGieJSsZag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YWpMOVY3aEtLMEFmai9M
            dC9PMS9XZGo1cTNnWWxZOE55Q21PSTZGc2p3Ck9FWm9Bc0V1NThqUUU0ODUzRDls
            UG1CbjN2ZC80VUYwQjNERW9IVXExUG8KLS0tIGF1K0w0ZXVLNWFaUGNCQ01YWEpy
            L1F5aU44cG1zRTVwSHB6dWZGUmhRS28KDlW22tC4eSrFJhAImxATi3K/nyVMNiFX
            EM7Y4F9McB+AOI9JrK3afdKUoLE3C5LIdjuw1+iQy7yAxh5ToBrn8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-06T13:16:03Z"
    mac: ENC[AES256_GCM,data:v9WUlm/YwzYhbh1c6jSCQOq8AsT7+UqVnjeuqLKKTacypC/AO/9j1o9EYuO+PMLh0WdolBBgmoKojL9YLI289YPMZ7stVC5YufA0YFBUbwWVB/rlu0v0N/DBQElYQm2ABwU2m8In8ulhBahjQwBCtKaVDP25h0hIsQ9KZFmrWV0=,iv:YGynxk/fS1Y5ZtAP1E73rpFUyVXy1dJaLn6eRYmJRmY=,tag:1PGkMeT7CG7WyxeGxluP1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
