apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
stringData:
    HASS_DARKSKY_API_KEY: ENC[AES256_GCM,data:WwdO88yIyAOQW9ME/apH4iwGANswJBLdBbCq,iv:L//hTqoHDPXKqzWDr+jZv+LPGYq3SSyJ3bSB+mBCd7w=,tag:x27Of5U9PRk8aAuf201IMQ==,type:str]
    HASS_ECOBEE_API_KEY: ENC[AES256_GCM,data:Yc5kztaBifDdoWfRFEWWt35hFDFWxBU/tJM=,iv:4x/fnRY95pvb5dkuXvkpBOWqIVNeGu3OBNBL3VpDYuE=,tag:SCOMS0dH1DKCOLBW/FD90Q==,type:str]
    HASS_ELEVATION: ENC[AES256_GCM,data:cdx6DRSVzPNVk5uhBYoyCwJGyrez,iv:sb1SKV1BRe8PKCc35RE3RbwTpxDRq7F+mYJph5gwNDQ=,tag:Gt9a+QyluMVP4Z7hN+Nh0w==,type:str]
    HASS_GOOGLE_PROJECT_ID: ENC[AES256_GCM,data:cwufgXKJ2K2r1+nI1PRCSGoFxc2YJD9y3xZr7mA=,iv:88hW0OcysFsqUa7AWTm6X0q6BxFI1d5fvPZ7psvNLfI=,tag:PkQHP2nOGYPO9JYO/QAWRw==,type:str]
    HASS_GOOGLE_SECURE_DEVICES_PIN: ENC[AES256_GCM,data:v6nFF2z0JBnNMgvDOCxKH822B7a1TbqHsIe8G2imDENkn5S/RQ==,iv:6B/MZaYng08Bi/l55IJHdLVAP+NqnmULsZE0ZOuC6NQ=,tag:1Cc6A9IvFz+1lr4qmUdAxg==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:OyDQShJts9iXdaP615oGWou3jbg=,iv:u3s0dMT2B/hQOGCQivBG6ZOSnbRgOvbR5y8MEOh1cgc=,tag:pL1WWwr5LpTRcRm4GOBBVw==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:eY0kNFVO7VYbdcZMKGpLorLV5OT/,iv:gt047yoRxgCul8F2zVcFiQ72cP66Hea2f1UbDSzfNPA=,tag:5W1hZCL4XZXVTDowby7mlw==,type:str]
    HASS_PIRATE_WEATHER_API_KEY: ENC[AES256_GCM,data:xtZmUc//aM1R1JA6NRifZ8ETv9sMnxl3FvAyISXUP0PbOQ==,iv:Fc3/pswI639YY3W+IqE6NrnwAmmOpJOqEE4qFi9JdH0=,tag:lMczhYX0Wsg/Is9dOHnqig==,type:str]
    HASS_SERVICEMONITOR_TOKEN: ENC[AES256_GCM,data:aFbcgs0RQA0gYOXdXQney7mJfoKrY5I1GrL6TwdHZK86gTOhMDvQzfF9LWrACTq5uNVhGK8QDwpescmO/qukBe8Sw60FpXEdaYjvAASf9pROnIugtVITJ4VaDNumn+vRm+R63raSphoQBmrfKEYi9JTI3IX8tSAFNI8ZswpZOKzb5rIP9DC+YD2GnxCRkW1rapUY9vmlUUO1PLa/duGs6xa+74RhmXf1vIFlSwPP4XqrvVuL73TP,iv:FPSlXZxBkUr9ywonQwisum5ntmElXZVr/v7tYvcKHRc=,tag:pxhKie7XBbRpTHoP6/UofA==,type:str]
    HA_TOKEN: ENC[AES256_GCM,data:ukLyHz0EgtllXBTCwnsEs/j7QI254iv0dA+pKZrBTlr9vHuyLuWjdH3u2RFrpVRnyzFP3EqzNKYFaIsOrU43LzIMOhd4tRbHIFhu0bElOgcrvvUAhD1mIH6cpHpv32BL7OJFHY8N1cLIiZ3d6Z0QmrTsra9xKDH2gw3gbTCUX2MqCJzyL0YnEZpU964U8bC/f2EAssOUUmChBZYGz5TIukZ2AQKSL4TxMrWv90MbTW+dPZkC/Nvr,iv:V1PV9XHJIBgtDKhOMLhx3rwy4rUJtVtliObNa0P2QMI=,tag:lbhhxTiXILVdDvF/yNo+gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlUlV3Slp1SzlqSE1BTVNI
            M1dTcWZDU3BFOW8zZHdBRGlkV1pMWmNpK2dzCkxiME9pNlBrSUMxS0FFZDFFRjVK
            WFNqbVRoamhmSnZEVnEvaGxNSkJBdm8KLS0tIGJVQkpId05VV2p3MFFhNEhUVU1Y
            Y2xZbjNBYnR2Qnp2MHB2TzZQZGthVlEK9oWHpoBWULCdsYL4QasmQBKlh78z+32X
            4CrlWP5vxoeFicRmHs1hwVGzJ4irWTOx77sGq5RL8eH9YK9xY4Fdyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-26T13:17:53Z"
    mac: ENC[AES256_GCM,data:wEnnFxOZLO8V0GIvLdZBhX4666OgyL2jOAC0VfQkqsHAhMwzpwH9xI5tEt2ish6QCiPDxaGGNo+R5hGVZ5rs1qsLd7Fs4Cen/ma6mByz2cwbhfM7mGQ+Tw2eNoUZg0L3WV6BCKeA36LGcSYOdo1Z4oSqdoPG8REIaV6J2MX278Q=,iv:B2LzAfAfcbn3EIgkbg/DNcHJ/j0QdJRndPK5Om5fKbw=,tag:d7pnpN4P3BbiE/eZ3jweKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
