apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:0Kq4AlNdj/GMWgfu8n4CPGu9Ir4d2ZZrYoooCQzHofRh0ZRrtIfQtljKynzx9p0Rxv83w8rpqMxNpsrKjkBNiClv1cWHJSxpyUqMsc7KfAZ2bF/nFkt5LlsL36OAcXWrdvGaXl+BgfTnjCGExq81zAUKRnsdFStdlUi3WVi3pCIXAYI9HLheEBpcu8CEp7WP8iSxsY1qxnzEDnoGSnDI79kYmmLf1AAYJ9l4o4kM1SVfNIeKK018T/dO3mBX7L3YxO4PGk2rX3QEkJevzREKR1Zqym+ERFPC3ImEWFegNKetnmOeX+EoBbmsFVblgHR5QBU00zimD0Ri+c6j0qIJfCEDuGC798odFCr7MrCEDXLHa0arSJbgYakwoGcc/5lBvppgVr1H3UJEsF7iY81YR8QBgw+m20DxxPcVgp2wmzPnrrYk3MviOI2RAQt+xFy1uN6gMVVwkR/XmUF5l1fjUDHKBZfaP6kziDySHGTaCXPRDXJZnS3ZMrG+EzXsFWM8cKLpK3SgqfjijoGQEUY7KJraivWWtg2oiOTU+wX+BM4/VSDJtZpuqwyTPpwXJH+l39N3dHKlp81CXMH+gHkjuq7akmb8yqI00EcSAdWai0Z+cg+s9hLdmJIzMyDS2P5pgE8y+MVuqjATetW0VCuEugR6ww7FWsfpGyU5gnF2diSORXuGsr3U9DnQCnBLo8ltc36EWIhEUTQsfUeNRrecl48mEIHUMeocBU60ogvH4uJt/78ZUjnCdd16Rr4XOnM/+md7hK1Y+p2eQHcFKLIFO5XXkPD3i5kEGs3qWevzS2GOXb343Jek5uENEpb+jkYf81r3sYFmR6ZThq2FMhFibX89E3Hqar7gNT3LQ3fr3kDldRCUq10aWQJfASJPtnMTkJiqSb3Hf+ARtySte2c4pqoJGLvHyUjZbGYzCP/AOnbxi9vb0Kl7rYue0eTvttX48Osw8eIqgmWnWuVwbbTk7ropAosCIqqEvqPOn5ECccFfpBJ5b9e34orhYu0CO3S8p3Uw5sF9IB5jTor83XhtrO1mu5TiNCw1aq34ci390CiSd5yUFE+7XCh4YHpzBxjdAQXLVKrf8xd8z5d7I8a4Uk1L6SzU4LwUjm6xFUem++cMuNdl/t977Dj5oqWhW0lBk2bHLFcpN5oKSZ7CNMWnUgOhBqWyL1u4rL5h1F+GFnaAtZN1hvP19i4rviyeFOnBNEbl+bMwYrB92wzpH1nZCsecQjep1SvPYJg5wDWgPlQLXsFMyp1aZDwcaSZJS6lEfY3bLSSluna/Hr8Q2kltayFxzgM94Daz+qcHQSwnO8/xabW73UOQj0rH81JAiQ+M276GMtStbCPw/TTQC1JQvITCnQByIK8c7Z4p7kuyCJtcL6n3lKW3Wtkd4R8mHkvupeegcHo97cv5RiYzkqTVICZioMDh38lKdSpKMzbjlFkKwNSlrekLrULxT2Ntgu0l3SGgAIP6XvXxAJaBBNCZC+r25KnaAxbfi9Q5XZbC98rEMN1rDiNju2mYy5MMNyLeTDj2UpYcGCMG877CdAhSf7RoX/EIrj1l2tOfIsm59vUrsWjKlu/15qg=,iv:PHNMXxnFzQqbiwoxGgsiBAKNuKC2pnDSmt6JoxV/1Gg=,tag:kbFLm/ZcZj//qquONfQTXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SEpLWXdIZ1o5S2NNTm5W
            VGcrTk9GU2RqWERRQXo5OXNSZDRpakFEcWs4CnpoQW9hQ2g2RE1OMkZLUmhTbjVG
            RUxwS0tJcS9DQmtPeWk3dVM1NkpPUjAKLS0tIHFFQnp1OGFVakdCYzNVZ2RxbE9n
            YURpZk9ROThFcnZnRXBDbjFvai85d3MKH/8TL/jsIiVb73P9DIeTSsBcP0Z42vwC
            slnpy1ydqqd9kqkbKC4/h2Dn/6ckiBdZbzDkAYmgLrSMpz6fJHv6Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-17T17:23:48Z"
    mac: ENC[AES256_GCM,data:vXq+5uw5TlNsmrpDHLcKixCAEUNM8r4m6RgRjlkMhSUKe/xYpnCWlSDVJsHxrsNaV7lyWR3ARST6lUl1l789qLEPZxbnawvrYLX0MMNj8dHrm674sf1R8ZoZRHWCEYeGD6hsLIL19Oj5A/dyql+HzUZG+D1WSWdIKPoJw46BRO8=,iv:Nb2mlVaFOAModiu8f5Q3DmXfLNIR2gfIkk/VQBhgH9Q=,tag:ZlEMaKlaymtkhLjUaKsbpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
