apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:UprAZE/hBiXkAb8jCzyN23Vkl2+C2fJW8wA+hEfl3WTmKj5T+AQfQKuQ8+QtRxZLJa6vlk8d66Weoiex+k4TN2HRx6id0pU4EXOj7FVEmz8TRCkYh4i11Hp4ukcWgJI7VXOowfhuO3XLlWdZzmvIptFmO+oSaoGYkLHNXGVYfigkYtCO1NTEKmBbvyuJDYMzhHpUUjUIVhWiK303qtO7tZNtIhfQK5Od2DT+3rIzxO4/I/I7HyeZmtW3lGBRYGT3w0hUuvmK+uv4PmUVb7MA0AMQIRJ0oCULZY0oM6YOwZ/H3MXMFGBw7RmnoyNGwPj1KiTnm1AgnPkUE2/+D8L+1shagc+PPq5es++rjzcoKZLu/VYrKuj9Sr+KzQF03WIX3aDVWJqg/QWyObTRey3cPbjX+WL+0uq57gHKkrYNWXxanfiymBAsOgrNI5WEsnHoUKDG4VG42eguBX4opchCpWKGFxA/gQ4x0o4Dy8018mOK9XFGnzTVHuwULvvj+L8fT4pPIT2NXu3ND3/gN67WW8m4QQ6OAVxuHv4owOoj9k2uwsOf94/r169Z9TEzjrOuwJZFJ7VLo0aRYPSAIxqe6s7c91dVEiLL4emOdw0unzmqBIHHfxOwZJAERb71FMR9hmxAMJLhcdwcAre3FLcMPO33GYGtY7tCGZ7XtdxPrG2IjwHZgzB3mvyqnpvgY5Cv1HONwovILqjVsgrYsYokgPRBM05ALBIIwapJ99NhY4nT1lm9Eo8WeTvy3Z5FuxMT5J87b1c7+yb1sGUeVFW0P/z9jKpKXML9Q/2cq+cAKLLB3i2VmC17PbgekOZOlxA190olpvPhjo7T2GjjGzs/sZO2KYSDSW71BTORvPg0QwCLEFE8kwWk8P296yEplm2WCC7db5ZUSZJoYgwWRcsmOFC3a3iglCe42O7nZR8xHzAUMK/0zpVUsJWqL3qAuTUgSURu/rVryDG2lBOtAEoF5l9N5JVBFI9E89I7ywwZPh7IBc1Qyf5I2S7tIG5zOic3gYhwkq+EtYcFdx1vmGvICy61dXQ1BUAxWH06/Dlp/l+qzq1y+S1nRD1NkTiGiJAF1QENbhDwrDg9h1T1A6IwwAjS1F74SONhuRq14N73LigAmrr8eVluu+tfE0huvaToIpNcLLn9Wvf11GUznwGP947bboknVfVbPdAAVrMBGjkSeqK7EGdPB8xEE1AMEka3Gc9blJ1vp1u56w0nshj/Y0zeCFEr3kMks0d5cKbxs4QqGA/goG9MprDPRQqkrEwWweAqFDZGzSpCwXITGW5X9yVaghwBunbbdtjOVAXJw83WEE+yoW7KA1bxethkyzE=,iv:Zd39AZFv20FMe+QesYW9hcrVCeOIJZaZE2rooGILets=,tag:qIoZCqutGS6gLBUYh0/0tA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SEpLWXdIZ1o5S2NNTm5W
            VGcrTk9GU2RqWERRQXo5OXNSZDRpakFEcWs4CnpoQW9hQ2g2RE1OMkZLUmhTbjVG
            RUxwS0tJcS9DQmtPeWk3dVM1NkpPUjAKLS0tIHFFQnp1OGFVakdCYzNVZ2RxbE9n
            YURpZk9ROThFcnZnRXBDbjFvai85d3MKH/8TL/jsIiVb73P9DIeTSsBcP0Z42vwC
            slnpy1ydqqd9kqkbKC4/h2Dn/6ckiBdZbzDkAYmgLrSMpz6fJHv6Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-21T03:51:53Z"
    mac: ENC[AES256_GCM,data:ICTqu/hkfBcqaBg5TTBth2boNk54Ry6RrWUVqnVMCekqzuWXeVDuI5l5XrlpwMSaKtWBznWgmzq9a1JqQQWCI3TmfqtcKYcHLUSLVELMU+q85tNjpS1tCKNZ/bkhBZR9Hy/BhqwwjcHD5ZmGAAC3AsT9DrLet/G8EFZaescaVRA=,iv:GgG2Svgug5s9pHbvafgE22V9cXxh2vT+jM7Ob3P9PCQ=,tag:PxJdo1NEMyduiY5o3zFwFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
