apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:anfbydkCI+0J2XkH2Q11e6+76/rGgzI9X6QxiiqSNaNoavfR8fDeHDdXMOJMhEK5b56V+tp1jEk6mmuAAptfnd6D3WAcJrFEW4Lq3+pfFX5DODWEyqE0XWpAdXHAwO8Nmfdah/Y1bKcVNk8C6LvilZLWS/bTOue4l90AimyaklNv8ShHOxzWn7xPdLHu8weHFsE1HAxhsNCDf19bkXTIxLSTnqa73WlJEJrcPth44zqgIvV1NZEtU3zgusRzcpjdl8c02/59j/YZHll2DwTTNTyxNfE66KKG1Shi5T4rmzlZ/f+aK1s71n5EmNc7mTRMkIXoUIUu0uYRG6hsSqcLvcOjDb5QLDl7CzlubTHtz8PA7nhDdTpTteR2aUMfyX63is0UXlzoKePk5GeNL3zEFrRNE2W1Q2oSsgyTH1yvE/r2PanYBFK+dz9iJ6YM3sIQfFcrxsu96NGgfxHllxk0oJX2OSQ58bnJ7fHLFwYWaXO3UntiikicvP8Cki0J11Fyexe654o+GBQLychkXTN40azbvGHBAMvVtP4jbb6cDx61Fb+SMto4Fny33cxOVH061ZEKqcsFGEBJdPscmByT8B/Wh5QcFFSKbJzjBPaKPQd0x3y8Kll1Yu8KSDXgkmEyRp3/vOq+FQM3eyc6vF80oZh7wFeNOPzB1ANwLX4i6t7ljgrGl4j/8JzCjhXTiXAYLhEB2potzRAmr2eH79qEQCGQCf+4qD+LqEqFPjArqj2C2AbeGiDekoV9lYDEe0eTQW45zX8RqzF2mTFjL5ZVZtdIBlGxd0+aZfK3leM4WKJnsKbt/q8SOQD6YhXAtz2hq/aDLcaLEN89ZaiyqU9rhDaWpnJS9ggmnN39EAdT/yWQg5rHPjDcakLqRpbGE8JvmRL8yojI0YXKSEP+mczlJnXf3YqH836FqlizaqWR4h2rZCKZekw3P3FB8htCamrhvS0BVT7HjTSx4dV4HSo+RdlDqhi08yrftVrwfFDL7M5eoidCYWgYtlFPKLvqDZ4Prv8NKs2VxN0dOPKE6/y/7WoqgsrqndM6dUHnQAlMEDVXSBNu+eVsgoKjg9NCOBYiFBAStJlWMpyCU0zVacIi1Ss7U4IY5cj2OVCDB1QRQwkVZ7bjw0ifSVIZV/HsO9AtVXfWUoXHgNispvpzsQnVt85dwIiW+HRbb1jOxGRthvdkxMU0S77i9NImQhX+opNoOCku9dF8lBqeHr0QfNveDSnNozE62N/JgnaqyXMheE+dUokNnBNMXbKD/JkGdF9ZRVnabfXhivdjSIUBb/Zp05HgTy/nWy6qtdB1HI0kkOFP6ZF2PhlzqNd3ZarFfm/B6k3QZQRf8ErnErsRvDDOjeiBZtStkeLWCcOlteMOeCYbFoZ7JqxWCcPZgvH2L/sKSu1X4bs4D4r3D/PxVlOrREsFLN/50Z58mtSIAdf8zxTMl/Llu/l56IDG1RUX+2tU9zA6QFG+wMnxACHhO7Z7QkNA+Gk+g18p5wtqWT6AiG5EcAEaBq+1wm1DSD5iUp8myFRRfSlBlWoFp1RIZuyr6lmWFQFWCHTob8XbK5dqnZ4m4Hmnm72JJtN/hVokRRbLNZYGKmo1,iv:7AcwQA5u6JlPROF7eu8FVT32qTd38VE1GzXCDwnFcu4=,tag:HEOajZqHF+igM9hmtsc3xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SEpLWXdIZ1o5S2NNTm5W
            VGcrTk9GU2RqWERRQXo5OXNSZDRpakFEcWs4CnpoQW9hQ2g2RE1OMkZLUmhTbjVG
            RUxwS0tJcS9DQmtPeWk3dVM1NkpPUjAKLS0tIHFFQnp1OGFVakdCYzNVZ2RxbE9n
            YURpZk9ROThFcnZnRXBDbjFvai85d3MKH/8TL/jsIiVb73P9DIeTSsBcP0Z42vwC
            slnpy1ydqqd9kqkbKC4/h2Dn/6ckiBdZbzDkAYmgLrSMpz6fJHv6Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-14T21:51:15Z"
    mac: ENC[AES256_GCM,data:osCJ9wCxTItEOlE4x8dADAxBXwaEpP3IDmEHz1nSGUk8ZFVDFgqQMpcjCQ9f+mlgVlehEqJdn92dK1LLngX4j4gtpr/RSN/1el8WSWeBd01iL/b7TpuBpBiv5rpjkoQLlmVaS0h9tB7NSLX2JNLkYCDowERtSPZvDHccJMaycTg=,iv:ni3XdQxFROWrRL+FMqNMs9Jx+gp1vN0oI4+ICHpcEq0=,tag:vmGK14FYzYk8DAA1vXgqrA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
