apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:smtSwJXF32YSTQpQ3Dv9YhCwtrW2HClOjdT3xPUbeT58aEd0WJWslFFwkEXv7td3NCO9GYCSIqEV5YW/g/FlVH1VDZQSVwI2Kq5BdBEOyajPA+0LzOU+hGeOWzUB2va0O79etPHvOF75MFNfzlLM0+hDZ1Iq9kLUUI5b8KcuqtnGbAcLPOyz/xT3j4A2yJ6mQYBNRmHN7D7fri9tBf7q0dCMYOu+h4fOcDKl5POS+eg0bEw5ev5+mTaP9EQl0xrndEowmW3t23b/OLeF3LC3/GVcJvRNu/1ix/2wy8JY26OJlp41j3JdREZ00SlwBQgZg3i3hXewgmYtWPhKZC0y3eQ5R4R823PyK5oM9VSAQTu1FQOUckpd/ZqU8USAAWJ/7ImfW5tJHZpTQgecxMpIBfiD0z3sZ8gXpJKw0eIMiS9GQDond0cxzKSfAPoHZpQ/1r0NHoZ6t4NLezlq2mu8mGFiXs32LR0p44Nq0n2OhQShvtijhj+OPYtX2lm+MjaNz3uvb7p6SErSlDSJBPrTc3qKGmqk6wHzdG2sC7h8nAXItfD1dVFk30e3NNDIywGtsDLpxOOvTbTg//eHh/H5hEZ4g2rbv/Nx8d+m4E8lsMJN5Ed26RzkTsPgCrmDvGZI4aulLSKVbFHnhhPtUalxnb9kms1Px1rEb7Pvjz5B47mtTND039rXjzq9xtV+Wbg1KtzqMjuwHFuoECfhrQ/BXvC0WmINOJ8l+RGN2c/gDll900D9Lyp0WN2mwMvPBw7uyPKVXkBioeuO/iOXzF8cK7cAADNpmeMs7sGS0A1UA73tOg7Sm3U4DrMLV/ez6B4xfLVXnUmiPp1XiFFV/8eGNX7TXyF1/oOFsUlezJasPHK15DfTUzgARoGmZlPFu8X5b/SsXE8PG7/tjsWt2cS+vzo0t+eCaKbR/0UE0S5MTanjFbMiDat3F5KVaMieTEbzwSCZpxeGDdMA4yarDyH5gilSdh0vdSmUuBLRVEXgvy21cI8lQGBmRA==,iv:IGa1YxaFja83VXkCdmnXgISMVJVjywbDBJDB2c/Qx7I=,tag:/wLx19n0l7KpCRtOw1LnEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SEpLWXdIZ1o5S2NNTm5W
            VGcrTk9GU2RqWERRQXo5OXNSZDRpakFEcWs4CnpoQW9hQ2g2RE1OMkZLUmhTbjVG
            RUxwS0tJcS9DQmtPeWk3dVM1NkpPUjAKLS0tIHFFQnp1OGFVakdCYzNVZ2RxbE9n
            YURpZk9ROThFcnZnRXBDbjFvai85d3MKH/8TL/jsIiVb73P9DIeTSsBcP0Z42vwC
            slnpy1ydqqd9kqkbKC4/h2Dn/6ckiBdZbzDkAYmgLrSMpz6fJHv6Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-08T19:51:43Z"
    mac: ENC[AES256_GCM,data:VnbmZXf1adSxWV7bbyXF2QAEmE4J2k0FlKov1BupHfK/miYva1yLs1Mpi9p3NY0V9gj3l9crAoZj0VPyCPoqiFkrn+sqcchy25dirX1A3WhSX9K1Aqcc+3mgdVGpo2+GxQ5mV+Z7xfKRIAKip28RNYCEHvfA14/UfrdpmVkGiQs=,iv:3FV//E/UJMu2PyTKcZytsSI8sTCbjSaxWYLq8Pe1RKY=,tag:J8XEBna9tlCE4MilpypAlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
