apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:UuWpZctgQ5I5x288NLiM2eh8QXXtxKG3GKTf3a5d0NQEe2poLlGyAcYF3x2RUerLfOy93U/VMYgR08980Y+uHCnmJxBlvTYEwSYQSB0S44xirPUh5mbhYmfyYlyYGJv8waWUB1xQddf9ILzdo3FJQs3hbM8yn5IGrYrMuxOKVHmK9v/XzV+OHG8j172Rf5Iyw3Wqdhi3roPixumN9SUxT8crvYZ+Hb8gdgMRx6kQg0pAJ6Cc+jiDmr4zjOlmjqH5Gyx21T4XXzWRMw++Yq/923VNHdj6ilGG9wSsGHh4MeMaYQooRdhbtB6LxOPFnq/c7w1MQth93hDGu3e5o3X4Q/in7N3n1opYJEq1XNWzUcfOHc9nIr5agSjvMyZNR+Prqr/nLU83xjHZ+SEpK+KaCNd7qNYrYDXXnv1CsjMYNZtySnKDyalTRJ96+54NU6bWb3MlD6k9J4iVZq81jwlMGgQzFbpLA+lJWmZaiVTQKYvHXQ7i4CvPe0bnCAL3pz69Bj9NGBCaDPWhfzTVGx3IEDYr/DJXcZasdXHoZWhq4W2NHgZJbBIkAsozIrPO1K2gDSz6IAyaCxwnoeSr3V7lAnTUrSFTWfZ84iWssNnAroE2v4qAuEMHY1sgrdh3vMeOMwNYgOc9yhM123k55Tvg/6CzN/3ZyzidHqPL/3HnIaIZjpEh/d6DTAsnneK84eZWEypomEiX0/K2rIvs1VFU3YgsjsP6h3t2TFgM/tbdB0EusCUYQAW8ECg0XzocJZm8+tdIHiWr6xWtPJjhC5cfmGn4BaZQ6eaAQlLwdEeqmbKMyC1J7l1rqdmd5g6Xw6KMx6Dzxj5i45y8f205jhTE/g7AjJdV9rsPpqRADE+MStq6q6pu3qruZ+BIBA/6/JpcxrqEshQcuh9EmaBgH7vqu+4e1Ad26+WJAMsx55LBUSTXx/l7m36JFdg8Ze56CrGxmIyarmnzl3yWwgEm8sZ1o6yBg6CGgD9nEkGfjnUGXo1Dn9g4RBOYOlGh93olromkDuLaHu1E4P/m++CO5abt/uv8PBsY97ZODyesBjkQTAGAvqme3JqmgIQxa2u6ChZKqch1Z4gUXWIvAhPdgiAGhDI2FVjwI1Zb6eJHhgqi6ZU8sje8oPH8NQN0+M4//nZt9E9IY2Ql4svCaYMdFDkCbXYzAg3NUMyKe7pIo9ZzpS+DcyYd9SUabAM7nciJfxkxx/M+5gBd5s0S2+OqcqbB9/+PAwdLDWYr6mPkhf3MLUmsLTq2o1Ar5XyRBrw1sD5/wGSN4SQroV2yRZ9JHgPPe1Tw0mcn0CT4nJ48v8S3jCjOxlr21bQ1y/nkJTYgwhtw056cmnUe5sd9nneLNJ5qsNoBG39JGBRMgQ==,iv:GuTnGx69/04wEMe0jNzX3InC3Y6o4vXOm7B4I7Fk8s0=,tag:OvUVKD9G3VBfR3ch0H/11w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SEpLWXdIZ1o5S2NNTm5W
            VGcrTk9GU2RqWERRQXo5OXNSZDRpakFEcWs4CnpoQW9hQ2g2RE1OMkZLUmhTbjVG
            RUxwS0tJcS9DQmtPeWk3dVM1NkpPUjAKLS0tIHFFQnp1OGFVakdCYzNVZ2RxbE9n
            YURpZk9ROThFcnZnRXBDbjFvai85d3MKH/8TL/jsIiVb73P9DIeTSsBcP0Z42vwC
            slnpy1ydqqd9kqkbKC4/h2Dn/6ckiBdZbzDkAYmgLrSMpz6fJHv6Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T12:01:59Z"
    mac: ENC[AES256_GCM,data:qenhSUCLXeyQg02xiPiCCku+ufEZlxr5+QEqg8waH3ofgynd7mEsWg7f+TIrd6EaLb3mIUi5l8L+DPZqk2TGY5BUWZnIqSDRY6EDjd2thrWrvZPCybybvf/ArddAjM+Ahhh0gUaQaTM4PG36yglRMe5U5Dlq+MM31vIDK+EoddQ=,iv:PI+VQfB+z325RiBIOZGMVnHn79BsPjdvsP/2UWI3svg=,tag:Z0uxA011AYctRBmLDjU31w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
