apiVersion: v1
kind: Secret
metadata:
    name: qbtools-secret
stringData:
    config.yaml: ENC[AES256_GCM,data:3lt1sPLDHOM0Sfx4P5d2O8DO1MNJXZC28d+jk/5fAkhCixywrXthAjyW0TkEej/CW8oGGSLUjWCv12Bbdt7XRMKLrWyscbpf6egCSqOvdvoYXiPjeZV6YAXsSqVJqpIkfsDSbtlToKi9xryqXl/c0ptKvC4SCOxy1B1qsxe10cpe9eee4s/YhMsl2yKZiJaVkT9wRrJiUkZz88mW1GBC1WvsnXUAb98I+RXuR33SS/6Fv6KO9EGBXGa8DX7ASHseFy2Obe+/KlMmwnPpS86dI9sEnUv9jDxSkNa+xRC/xnx6ziVG0OFbpWLWbTyPcrsv7TMhXG92jhF+DFL79aK/CznWXYVsznGkR2dQMWEXazB+SUP+117mTE0Xzd68niC/YIEes39JM7oPXXCzJV1IpP16lwJzq8036t5OkVM5S1ED25HkH1SKoqRoJbUoFsubHhuH/tpiG6QsbmPGeIDZUfh0+KiPaysz/8OqgwJNe2Cq1Ww9YTXBZac7tyjD36tjED6ewhaVm51IF9XIfxFQBV2Dpx0gns8CSmL2pQLhjucS/V3kGDQnPq5FHmchANX1ee8Bc18b+p/+8eJbDL7hyQSI+EzxE0Ow22CEMzeP1aH6a79gNWCqorggQYSiDmPATZrvNjYk9Xi12XatH79L/AVda3PKSh+GlVVjB/79pbVavfv+fVLHkAV5Dy5vzgPfkY7jvjroapHt/v75dvEhIS598iXAe6Q41xWzBo+MiGgWzYDTgIdGxqRrDa098FgKFZofm/9nFa07IxdtCM9+stOEKw0uxco64xta4zIQgE0tn7AFemcMeQ1PxzHseXhfBDMKsoARGHLdbmjmDC32HnIEWkJMnYQR1qDSNqwY6xMiNb9hgyiEwhZLC7d7+suYe+DGtpb6ePXooz3jBM5ppxwdvL6jqMxAfY1rJeSe8vPHmaUEYBQKMKAVnP+GKuEUwJvJYeBaW+HNisgUn7hKSfh9JJ2dyGVLKXQmWRq/rAVhUopJPfRZs8BfoZpWtJmcLnT4D7FSKZrAg7YdDyJnCbvwpUcsUI8g3lneUXMbvsE3x6nUvcUdf3px0+Iwmdazynb/CWp100JT89Yv6s11T/GFjEkv8G9It7cu3kua3o1OaQfUSY1lYym9hTFHR/J4DDCJ+ANU5Ms77hYu4wrK6fuAOTfEfOZ4awb1Tzc396szaTP/7vqV1X7JYMfSaNtPAjcZr3Mwc5W501k/P3pER//xekiwvdOxD5ly866IfCB29bITE/94u9I=,iv:iTrcy/JMh4SWiy5DWdA1pd3mV1yKnQWOXLjm2yqDZts=,tag:dzMpNg2/6fZZxvuef/96Vw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SEpLWXdIZ1o5S2NNTm5W
            VGcrTk9GU2RqWERRQXo5OXNSZDRpakFEcWs4CnpoQW9hQ2g2RE1OMkZLUmhTbjVG
            RUxwS0tJcS9DQmtPeWk3dVM1NkpPUjAKLS0tIHFFQnp1OGFVakdCYzNVZ2RxbE9n
            YURpZk9ROThFcnZnRXBDbjFvai85d3MKH/8TL/jsIiVb73P9DIeTSsBcP0Z42vwC
            slnpy1ydqqd9kqkbKC4/h2Dn/6ckiBdZbzDkAYmgLrSMpz6fJHv6Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-18T15:07:03Z"
    mac: ENC[AES256_GCM,data:RLsLXTcr6QXxrWFTI3yEmaxHTutgOU6DKbFJkwsCwG/v10jhiji940Yi2Ama3PeM2rV9MPrBms4mZAtveaGCbTDWJFRHJaMS6KEUlRWJm4t6eP1DJK2JKMkW2QrCHTkxJ3jApWR2+n3Ffeu0DzQsPeImHPQxVYmcaedsrsBb2IQ=,iv:zSGaSguqSz6fOU2Yrqg+GNhZTPP/1Y+9HSs/lpcW20I=,tag:uT5mrbgtBOkqaF829nb74w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
