---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-proxy
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled

  dependsOn:
    - name: immich
      namespace: default

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    controllers:
      immich-proxy:
        containers:
          app:
            image:
              repository: alangrainger/immich-public-proxy
              tag: 1.11.1

            env:
              IMMICH_URL: http://immich-server.default.svc.cluster.local:2283

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthcheck
                    port: &port 3000
                  failureThreshold: 5
                  periodSeconds: 10
              readiness: *probes

            resources:
              requests:
                cpu: 100m
                memory: 250Mi

    service:
      app:
        controller: immich-proxy
        enabled: true
        primary: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            primary: true
            port: *port
            protocol: HTTP

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        className: external
        hosts:
          - host: "photos-share.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
