apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:6fZIdJNG2iUMoBsdxzM3zv0saBgK3nFlePFFnUh1Tq3TwWK8Av4J5Q==,iv:3PlEDNBXFZBqu6yECzotIllZ2/HlJNKp/vSOvFRHyy4=,tag:0dxRwpJfSo2R8gcKnUR5dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMzJpcVpmOGgxcjlZam5x
            YlVweDhpQllKMGI4d09CeFk3YTg5VEljdlI0Cnp5NXpzd040MUkxdUtoaVI2S05p
            VW5BRERIQ2VScVVONHZocHY4TlBUMDQKLS0tIFlMY3MyeTZEVTNWR2UzZUFkYkw4
            RTZMdGsvQXBrd0s1WUQveDFCOEZ3bEEKm9xJw3Ms1ozcg8xUjDQSPJCoUBqmUFqV
            P2XRIldrzUDCXaoX14mjpCJ3WacXEyAw6+ZwhphC0T07zEq+GVLUIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T15:34:41Z"
    mac: ENC[AES256_GCM,data:FiC4WxUKOFDfRZhtTCyW3wDUw+/7dJpsrfLJxdVhMQr4kxWdPbU+uB6/R/HNe7Ibe2QB0tb4HWg05XmrFKLoHs9zF554hUic5qqPDlS8omytqmFPjpf8MVfSD9HmZm35aOWtSXVMYbD7GXz9A7pjYdj34/kcAszL5lsm507j7MQ=,iv:ATs41WLEaf6zZdyS3ddr5R78pmIwJpkKPJ7x4IVi690=,tag:1sAwsRSnUtl7aPJ/iTxscw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
