apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:LoWV55c7ujZwhp43xRKinGsxxHHte7DZc+atj5EW4vLtS7HFV5T0uA==,iv:y5eRm5VwAlUN1Xfb7gYv/g8T2Aim9EJaTtKa3YDAdFo=,tag:/koabRzb0ER0CpWvmtzHbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOXlQZUlhL0NrSEo0Wmd2
            R1h2SVY1NkdZb2NNb3Jnc3Npd1dEYTJ6SzJRCndzMWF1bDZEN1htNytTR29IMWRB
            bEVZRW11MXpvcXp4NEJHaVFjMnNjMmMKLS0tIHBNdDB5encyb0JWOURoZzB2bnJ2
            cUNDeXRXVStsR2hBTHFtWXE4R2swRkEKHKHMrXhtp6JyUnz+o1NfRqJUOi4MxaO5
            WnNO+WNTwCrN+Ch6gMsXHHMcxEwfJdDPSlK/AwLVa2XCzZdd3RbM1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T16:25:59Z"
    mac: ENC[AES256_GCM,data:XrnFumJy2wWTwhCPtjrg81u7T7w4kcvxkSpeozXUUm8X98Fp0uGPWKww5/L/e1fc1rnypA8PfP0+0UUlEdbG6TEwEz4Hx8pnnFgrsJxbRyQQ2F5+99VB764/rIEOTFUWHmDcW6iqhGp6/a5qwaJiCTDAoRp262Jx7frMbqgxFsc=,iv:BspUiKKOrzn1+C3O85GkKsmNC8WW7c5oYF+u/c8j7+o=,tag:u9TqzXDck4ydZPcp8a3zCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
